package spotify

import (
	"context"
	"fmt"
	"reflect"
	"strings"
	"testing"

	"github.com/mike-webster/spotify-views/keys"
	"github.com/stretchr/testify/assert"
)

func TestGetRecommendations(t *testing.T) {
	seeds := map[string][]string{KeySeedArtists: {"1234", "1235"}}
	t.Run("TestParseRecommendationsRequest", func(t *testing.T) {
		ctx := context.Background()
		t.Run("no token", func(t *testing.T) {
			_, err := parseRecommendationsRequest(ctx, seeds)
			assert.Equal(t, reflect.TypeOf(ErrNoToken("")), reflect.TypeOf(err))
		})

		token := "tok"
		ctx = context.WithValue(ctx, keys.ContextSpotifyAccessToken, token)

		t.Run("token gets stored in header", func(t *testing.T) {
			req, err := parseRecommendationsRequest(ctx, seeds)
			assert.Nil(t, err)
			assert.Equal(t, req.Header.Get("Authorization"), fmt.Sprint("Bearer ", token))
		})
	})

	t.Run("TestRecommendationsResposne", func(t *testing.T) {
		t.Run("happy path", func(t *testing.T) {
			bytes := []byte(getRecommendationsPayload)

			as, err := parseReommendationsResponse(&bytes)
			assert.Nil(t, err)
			assert.NotNil(t, as)
		})

		t.Run("bad body", func(t *testing.T) {
			bytes := []byte("fdakslfjda;klfjad;kjadl;")
			_, err := parseReommendationsResponse(&bytes)
			assert.NotNil(t, err)
		})
	})

	t.Run("TestMainMethod", func(t *testing.T) {

	})
}

func TestGetRecommendationsURL(t *testing.T) {
	url := "https://api.spotify.com/v1/recommendations"
	ids := []string{"ids1", "ids2"}
	t.Run("TestArtists", func(t *testing.T) {
		exp := fmt.Sprint(url, "?seed_artists=", strings.Join(ids, ","))
		assert.Equal(t, exp, getRecommendationsURL(context.Background(), map[string][]string{KeySeedArtists: {ids[0], ids[1]}}))
	})
	t.Run("TestTracks", func(t *testing.T) {
		exp := fmt.Sprint(url, "?seed_tracks=", strings.Join(ids, ","))
		assert.Equal(t, exp, getRecommendationsURL(context.Background(), map[string][]string{KeySeedTracks: {ids[0], ids[1]}}))
	})
	t.Run("TestGenres", func(t *testing.T) {
		exp := fmt.Sprint(url, "?seed_genres=", strings.Join(ids, ","))
		assert.Equal(t, exp, getRecommendationsURL(context.Background(), map[string][]string{KeySeedGenres: {ids[0], ids[1]}}))
	})
}

var (
	getRecommendationsPayload = `{
		"tracks": [
		  {
			"album": {
			  "album_type": "ALBUM",
			  "artists": [
				{
				  "external_urls": {
					"spotify": "https://open.spotify.com/artist/7oPftvlwr6VrsViSDV7fJY"
				  },
				  "href": "https://api.spotify.com/v1/artists/7oPftvlwr6VrsViSDV7fJY",
				  "id": "7oPftvlwr6VrsViSDV7fJY",
				  "name": "Green Day",
				  "type": "artist",
				  "uri": "spotify:artist:7oPftvlwr6VrsViSDV7fJY"
				}
			  ],
			  "available_markets": [
				"AD",
				"AE",
				"AG",
				"AL",
				"AM",
				"AO",
				"AR",
				"AT",
				"AU",
				"AZ",
				"BA",
				"BB",
				"BD",
				"BE",
				"BF",
				"BG",
				"BH",
				"BI",
				"BJ",
				"BN",
				"BO",
				"BR",
				"BS",
				"BT",
				"BW",
				"BY",
				"BZ",
				"CA",
				"CH",
				"CI",
				"CL",
				"CM",
				"CO",
				"CR",
				"CV",
				"CW",
				"CY",
				"CZ",
				"DE",
				"DJ",
				"DK",
				"DM",
				"DO",
				"DZ",
				"EC",
				"EE",
				"EG",
				"ES",
				"FI",
				"FJ",
				"FM",
				"FR",
				"GA",
				"GB",
				"GD",
				"GE",
				"GH",
				"GM",
				"GN",
				"GQ",
				"GR",
				"GT",
				"GW",
				"GY",
				"HK",
				"HN",
				"HR",
				"HT",
				"HU",
				"ID",
				"IE",
				"IL",
				"IN",
				"IS",
				"IT",
				"JM",
				"JO",
				"JP",
				"KE",
				"KG",
				"KH",
				"KI",
				"KM",
				"KN",
				"KR",
				"KW",
				"KZ",
				"LA",
				"LB",
				"LC",
				"LI",
				"LK",
				"LR",
				"LS",
				"LT",
				"LU",
				"LV",
				"MA",
				"MC",
				"MD",
				"ME",
				"MG",
				"MH",
				"MK",
				"ML",
				"MN",
				"MO",
				"MR",
				"MT",
				"MU",
				"MV",
				"MW",
				"MX",
				"MY",
				"MZ",
				"NA",
				"NE",
				"NG",
				"NI",
				"NL",
				"NO",
				"NP",
				"NR",
				"NZ",
				"OM",
				"PA",
				"PE",
				"PG",
				"PH",
				"PK",
				"PL",
				"PS",
				"PT",
				"PW",
				"PY",
				"QA",
				"RO",
				"RS",
				"RU",
				"RW",
				"SA",
				"SB",
				"SC",
				"SE",
				"SG",
				"SI",
				"SK",
				"SL",
				"SM",
				"SN",
				"SR",
				"ST",
				"SV",
				"SZ",
				"TD",
				"TG",
				"TH",
				"TL",
				"TN",
				"TO",
				"TR",
				"TT",
				"TV",
				"TW",
				"TZ",
				"UA",
				"UG",
				"US",
				"UY",
				"UZ",
				"VC",
				"VN",
				"VU",
				"WS",
				"XK",
				"ZA",
				"ZM",
				"ZW"
			  ],
			  "external_urls": {
				"spotify": "https://open.spotify.com/album/5dN7F9DV0Qg1XRdIgW8rke"
			  },
			  "href": "https://api.spotify.com/v1/albums/5dN7F9DV0Qg1XRdIgW8rke",
			  "id": "5dN7F9DV0Qg1XRdIgW8rke",
			  "images": [
				{
				  "height": 640,
				  "url": "https://i.scdn.co/image/ab67616d0000b27308a1b1e0674086d3f1995e1b",
				  "width": 640
				},
				{
				  "height": 300,
				  "url": "https://i.scdn.co/image/ab67616d00001e0208a1b1e0674086d3f1995e1b",
				  "width": 300
				},
				{
				  "height": 64,
				  "url": "https://i.scdn.co/image/ab67616d0000485108a1b1e0674086d3f1995e1b",
				  "width": 64
				}
			  ],
			  "name": "American Idiot",
			  "release_date": "2004-09-21",
			  "release_date_precision": "day",
			  "total_tracks": 9,
			  "type": "album",
			  "uri": "spotify:album:5dN7F9DV0Qg1XRdIgW8rke"
			},
			"artists": [
			  {
				"external_urls": {
				  "spotify": "https://open.spotify.com/artist/7oPftvlwr6VrsViSDV7fJY"
				},
				"href": "https://api.spotify.com/v1/artists/7oPftvlwr6VrsViSDV7fJY",
				"id": "7oPftvlwr6VrsViSDV7fJY",
				"name": "Green Day",
				"type": "artist",
				"uri": "spotify:artist:7oPftvlwr6VrsViSDV7fJY"
			  }
			],
			"available_markets": [
			  "AD",
			  "AE",
			  "AG",
			  "AL",
			  "AM",
			  "AO",
			  "AR",
			  "AT",
			  "AU",
			  "AZ",
			  "BA",
			  "BB",
			  "BD",
			  "BE",
			  "BF",
			  "BG",
			  "BH",
			  "BI",
			  "BJ",
			  "BN",
			  "BO",
			  "BR",
			  "BS",
			  "BT",
			  "BW",
			  "BY",
			  "BZ",
			  "CA",
			  "CH",
			  "CI",
			  "CL",
			  "CM",
			  "CO",
			  "CR",
			  "CV",
			  "CW",
			  "CY",
			  "CZ",
			  "DE",
			  "DJ",
			  "DK",
			  "DM",
			  "DO",
			  "DZ",
			  "EC",
			  "EE",
			  "EG",
			  "ES",
			  "FI",
			  "FJ",
			  "FM",
			  "FR",
			  "GA",
			  "GB",
			  "GD",
			  "GE",
			  "GH",
			  "GM",
			  "GN",
			  "GQ",
			  "GR",
			  "GT",
			  "GW",
			  "GY",
			  "HK",
			  "HN",
			  "HR",
			  "HT",
			  "HU",
			  "ID",
			  "IE",
			  "IL",
			  "IN",
			  "IS",
			  "IT",
			  "JM",
			  "JO",
			  "JP",
			  "KE",
			  "KG",
			  "KH",
			  "KI",
			  "KM",
			  "KN",
			  "KR",
			  "KW",
			  "KZ",
			  "LA",
			  "LB",
			  "LC",
			  "LI",
			  "LK",
			  "LR",
			  "LS",
			  "LT",
			  "LU",
			  "LV",
			  "MA",
			  "MC",
			  "MD",
			  "ME",
			  "MG",
			  "MH",
			  "MK",
			  "ML",
			  "MN",
			  "MO",
			  "MR",
			  "MT",
			  "MU",
			  "MV",
			  "MW",
			  "MX",
			  "MY",
			  "MZ",
			  "NA",
			  "NE",
			  "NG",
			  "NI",
			  "NL",
			  "NO",
			  "NP",
			  "NR",
			  "NZ",
			  "OM",
			  "PA",
			  "PE",
			  "PG",
			  "PH",
			  "PK",
			  "PL",
			  "PS",
			  "PT",
			  "PW",
			  "PY",
			  "QA",
			  "RO",
			  "RS",
			  "RU",
			  "RW",
			  "SA",
			  "SB",
			  "SC",
			  "SE",
			  "SG",
			  "SI",
			  "SK",
			  "SL",
			  "SM",
			  "SN",
			  "SR",
			  "ST",
			  "SV",
			  "SZ",
			  "TD",
			  "TG",
			  "TH",
			  "TL",
			  "TN",
			  "TO",
			  "TR",
			  "TT",
			  "TV",
			  "TW",
			  "TZ",
			  "UA",
			  "UG",
			  "US",
			  "UY",
			  "UZ",
			  "VC",
			  "VN",
			  "VU",
			  "WS",
			  "XK",
			  "ZA",
			  "ZM",
			  "ZW"
			],
			"disc_number": 1,
			"duration_ms": 285653,
			"explicit": false,
			"external_ids": {
			  "isrc": "USRE10400992"
			},
			"external_urls": {
			  "spotify": "https://open.spotify.com/track/3ZffCQKLFLUvYM59XKLbVm"
			},
			"href": "https://api.spotify.com/v1/tracks/3ZffCQKLFLUvYM59XKLbVm",
			"id": "3ZffCQKLFLUvYM59XKLbVm",
			"is_local": false,
			"name": "Wake Me up When September Ends",
			"popularity": 77,
			"preview_url": "https://p.scdn.co/mp3-preview/a83eedd6b982d4afdc2ceaeb458f471118ad78aa?cid=db8c415a273c4ffc9286e12ff24b8b9f",
			"track_number": 7,
			"type": "track",
			"uri": "spotify:track:3ZffCQKLFLUvYM59XKLbVm"
		  },
		  {
			"album": {
			  "album_type": "ALBUM",
			  "artists": [
				{
				  "external_urls": {
					"spotify": "https://open.spotify.com/artist/5gWhlJBlLQGLOgYWO8lwCU"
				  },
				  "href": "https://api.spotify.com/v1/artists/5gWhlJBlLQGLOgYWO8lwCU",
				  "id": "5gWhlJBlLQGLOgYWO8lwCU",
				  "name": "Saves The Day",
				  "type": "artist",
				  "uri": "spotify:artist:5gWhlJBlLQGLOgYWO8lwCU"
				}
			  ],
			  "available_markets": [
			  ],
			  "external_urls": {
				"spotify": "https://open.spotify.com/album/44cRFV6WtHD4T0HK7EEaDN"
			  },
			  "href": "https://api.spotify.com/v1/albums/44cRFV6WtHD4T0HK7EEaDN",
			  "id": "44cRFV6WtHD4T0HK7EEaDN",
			  "images": [
				{
				  "height": 640,
				  "url": "https://i.scdn.co/image/ab67616d0000b2733157a76419d826b1bb13f2ef",
				  "width": 640
				},
				{
				  "height": 300,
				  "url": "https://i.scdn.co/image/ab67616d00001e023157a76419d826b1bb13f2ef",
				  "width": 300
				},
				{
				  "height": 64,
				  "url": "https://i.scdn.co/image/ab67616d000048513157a76419d826b1bb13f2ef",
				  "width": 64
				}
			  ],
			  "name": "Stay What You Are",
			  "release_date": "2001-07-10",
			  "release_date_precision": "day",
			  "total_tracks": 11,
			  "type": "album",
			  "uri": "spotify:album:44cRFV6WtHD4T0HK7EEaDN"
			},
			"artists": [
			  {
				"external_urls": {
				  "spotify": "https://open.spotify.com/artist/5gWhlJBlLQGLOgYWO8lwCU"
				},
				"href": "https://api.spotify.com/v1/artists/5gWhlJBlLQGLOgYWO8lwCU",
				"id": "5gWhlJBlLQGLOgYWO8lwCU",
				"name": "Saves The Day",
				"type": "artist",
				"uri": "spotify:artist:5gWhlJBlLQGLOgYWO8lwCU"
			  }
			],
			"available_markets": [
			],
			"disc_number": 1,
			"duration_ms": 189693,
			"explicit": false,
			"external_ids": {
			  "isrc": "USVR90295301"
			},
			"external_urls": {
			  "spotify": "https://open.spotify.com/track/5YHWXpglx1Tplpy0T6o4Hm"
			},
			"href": "https://api.spotify.com/v1/tracks/5YHWXpglx1Tplpy0T6o4Hm",
			"id": "5YHWXpglx1Tplpy0T6o4Hm",
			"is_local": false,
			"name": "At Your Funeral",
			"popularity": 0,
			"preview_url": null,
			"track_number": 1,
			"type": "track",
			"uri": "spotify:track:5YHWXpglx1Tplpy0T6o4Hm"
		  },
		  {
			"album": {
			  "album_type": "ALBUM",
			  "artists": [
				{
				  "external_urls": {
					"spotify": "https://open.spotify.com/artist/7FBcuc1gsnv6Y1nwFtNRCb"
				  },
				  "href": "https://api.spotify.com/v1/artists/7FBcuc1gsnv6Y1nwFtNRCb",
				  "id": "7FBcuc1gsnv6Y1nwFtNRCb",
				  "name": "My Chemical Romance",
				  "type": "artist",
				  "uri": "spotify:artist:7FBcuc1gsnv6Y1nwFtNRCb"
				}
			  ],
			  "available_markets": [
				"AD",
				"AE",
				"AG",
				"AL",
				"AM",
				"AO",
				"AR",
				"AT",
				"AU",
				"AZ",
				"BA",
				"BB",
				"BD",
				"BE",
				"BF",
				"BG",
				"BH",
				"BI",
				"BJ",
				"BN",
				"BO",
				"BR",
				"BS",
				"BT",
				"BW",
				"BY",
				"BZ",
				"CA",
				"CH",
				"CI",
				"CL",
				"CM",
				"CO",
				"CR",
				"CV",
				"CW",
				"CY",
				"CZ",
				"DE",
				"DJ",
				"DK",
				"DM",
				"DO",
				"DZ",
				"EC",
				"EE",
				"EG",
				"ES",
				"FI",
				"FJ",
				"FM",
				"FR",
				"GA",
				"GB",
				"GD",
				"GE",
				"GH",
				"GM",
				"GN",
				"GQ",
				"GR",
				"GT",
				"GW",
				"GY",
				"HK",
				"HN",
				"HR",
				"HT",
				"HU",
				"ID",
				"IE",
				"IL",
				"IN",
				"IS",
				"IT",
				"JM",
				"JO",
				"JP",
				"KE",
				"KG",
				"KH",
				"KI",
				"KM",
				"KN",
				"KR",
				"KW",
				"KZ",
				"LA",
				"LB",
				"LC",
				"LI",
				"LK",
				"LR",
				"LS",
				"LT",
				"LU",
				"LV",
				"MA",
				"MC",
				"MD",
				"ME",
				"MG",
				"MH",
				"MK",
				"ML",
				"MN",
				"MO",
				"MR",
				"MT",
				"MU",
				"MV",
				"MW",
				"MX",
				"MY",
				"MZ",
				"NA",
				"NE",
				"NG",
				"NI",
				"NL",
				"NO",
				"NP",
				"NR",
				"NZ",
				"OM",
				"PA",
				"PE",
				"PG",
				"PH",
				"PK",
				"PL",
				"PS",
				"PT",
				"PW",
				"PY",
				"QA",
				"RO",
				"RS",
				"RU",
				"RW",
				"SA",
				"SB",
				"SC",
				"SE",
				"SG",
				"SI",
				"SK",
				"SL",
				"SM",
				"SN",
				"SR",
				"ST",
				"SV",
				"SZ",
				"TD",
				"TG",
				"TH",
				"TL",
				"TN",
				"TO",
				"TR",
				"TT",
				"TV",
				"TW",
				"TZ",
				"UA",
				"UG",
				"US",
				"UY",
				"UZ",
				"VC",
				"VN",
				"VU",
				"WS",
				"XK",
				"ZA",
				"ZM",
				"ZW"
			  ],
			  "external_urls": {
				"spotify": "https://open.spotify.com/album/3DuiGV3J09SUhvp8gqNx8h"
			  },
			  "href": "https://api.spotify.com/v1/albums/3DuiGV3J09SUhvp8gqNx8h",
			  "id": "3DuiGV3J09SUhvp8gqNx8h",
			  "images": [
				{
				  "height": 640,
				  "url": "https://i.scdn.co/image/ab67616d0000b273cab7ae4868e9f9ce6bdfdf43",
				  "width": 640
				},
				{
				  "height": 300,
				  "url": "https://i.scdn.co/image/ab67616d00001e02cab7ae4868e9f9ce6bdfdf43",
				  "width": 300
				},
				{
				  "height": 64,
				  "url": "https://i.scdn.co/image/ab67616d00004851cab7ae4868e9f9ce6bdfdf43",
				  "width": 64
				}
			  ],
			  "name": "Three Cheers for Sweet Revenge",
			  "release_date": "2004-06-08",
			  "release_date_precision": "day",
			  "total_tracks": 13,
			  "type": "album",
			  "uri": "spotify:album:3DuiGV3J09SUhvp8gqNx8h"
			},
			"artists": [
			  {
				"external_urls": {
				  "spotify": "https://open.spotify.com/artist/7FBcuc1gsnv6Y1nwFtNRCb"
				},
				"href": "https://api.spotify.com/v1/artists/7FBcuc1gsnv6Y1nwFtNRCb",
				"id": "7FBcuc1gsnv6Y1nwFtNRCb",
				"name": "My Chemical Romance",
				"type": "artist",
				"uri": "spotify:artist:7FBcuc1gsnv6Y1nwFtNRCb"
			  }
			],
			"available_markets": [
			  "AD",
			  "AE",
			  "AG",
			  "AL",
			  "AM",
			  "AO",
			  "AR",
			  "AT",
			  "AU",
			  "AZ",
			  "BA",
			  "BB",
			  "BD",
			  "BE",
			  "BF",
			  "BG",
			  "BH",
			  "BI",
			  "BJ",
			  "BN",
			  "BO",
			  "BR",
			  "BS",
			  "BT",
			  "BW",
			  "BY",
			  "BZ",
			  "CA",
			  "CH",
			  "CI",
			  "CL",
			  "CM",
			  "CO",
			  "CR",
			  "CV",
			  "CW",
			  "CY",
			  "CZ",
			  "DE",
			  "DJ",
			  "DK",
			  "DM",
			  "DO",
			  "DZ",
			  "EC",
			  "EE",
			  "EG",
			  "ES",
			  "FI",
			  "FJ",
			  "FM",
			  "FR",
			  "GA",
			  "GB",
			  "GD",
			  "GE",
			  "GH",
			  "GM",
			  "GN",
			  "GQ",
			  "GR",
			  "GT",
			  "GW",
			  "GY",
			  "HK",
			  "HN",
			  "HR",
			  "HT",
			  "HU",
			  "ID",
			  "IE",
			  "IL",
			  "IN",
			  "IS",
			  "IT",
			  "JM",
			  "JO",
			  "JP",
			  "KE",
			  "KG",
			  "KH",
			  "KI",
			  "KM",
			  "KN",
			  "KR",
			  "KW",
			  "KZ",
			  "LA",
			  "LB",
			  "LC",
			  "LI",
			  "LK",
			  "LR",
			  "LS",
			  "LT",
			  "LU",
			  "LV",
			  "MA",
			  "MC",
			  "MD",
			  "ME",
			  "MG",
			  "MH",
			  "MK",
			  "ML",
			  "MN",
			  "MO",
			  "MR",
			  "MT",
			  "MU",
			  "MV",
			  "MW",
			  "MX",
			  "MY",
			  "MZ",
			  "NA",
			  "NE",
			  "NG",
			  "NI",
			  "NL",
			  "NO",
			  "NP",
			  "NR",
			  "NZ",
			  "OM",
			  "PA",
			  "PE",
			  "PG",
			  "PH",
			  "PK",
			  "PL",
			  "PS",
			  "PT",
			  "PW",
			  "PY",
			  "QA",
			  "RO",
			  "RS",
			  "RU",
			  "RW",
			  "SA",
			  "SB",
			  "SC",
			  "SE",
			  "SG",
			  "SI",
			  "SK",
			  "SL",
			  "SM",
			  "SN",
			  "SR",
			  "ST",
			  "SV",
			  "SZ",
			  "TD",
			  "TG",
			  "TH",
			  "TL",
			  "TN",
			  "TO",
			  "TR",
			  "TT",
			  "TV",
			  "TW",
			  "TZ",
			  "UA",
			  "UG",
			  "US",
			  "UY",
			  "UZ",
			  "VC",
			  "VN",
			  "VU",
			  "WS",
			  "XK",
			  "ZA",
			  "ZM",
			  "ZW"
			],
			"disc_number": 1,
			"duration_ms": 232466,
			"explicit": false,
			"external_ids": {
			  "isrc": "USRE10400668"
			},
			"external_urls": {
			  "spotify": "https://open.spotify.com/track/6gLn8QhAYL4dEwdpVjfCPl"
			},
			"href": "https://api.spotify.com/v1/tracks/6gLn8QhAYL4dEwdpVjfCPl",
			"id": "6gLn8QhAYL4dEwdpVjfCPl",
			"is_local": false,
			"name": "I Never Told You What I Do for a Living",
			"popularity": 57,
			"preview_url": "https://p.scdn.co/mp3-preview/efb02a52efb552fd2017700aba65a406976c9378?cid=db8c415a273c4ffc9286e12ff24b8b9f",
			"track_number": 13,
			"type": "track",
			"uri": "spotify:track:6gLn8QhAYL4dEwdpVjfCPl"
		  },
		  {
			"album": {
			  "album_type": "SINGLE",
			  "artists": [
				{
				  "external_urls": {
					"spotify": "https://open.spotify.com/artist/14r9dR01KeBLFfylVSKCZQ"
				  },
				  "href": "https://api.spotify.com/v1/artists/14r9dR01KeBLFfylVSKCZQ",
				  "id": "14r9dR01KeBLFfylVSKCZQ",
				  "name": "Damien Rice",
				  "type": "artist",
				  "uri": "spotify:artist:14r9dR01KeBLFfylVSKCZQ"
				}
			  ],
			  "available_markets": [
				"AD",
				"AE",
				"AG",
				"AL",
				"AM",
				"AO",
				"AR",
				"AT",
				"AU",
				"AZ",
				"BA",
				"BB",
				"BD",
				"BE",
				"BF",
				"BG",
				"BH",
				"BI",
				"BJ",
				"BN",
				"BO",
				"BR",
				"BS",
				"BT",
				"BW",
				"BY",
				"BZ",
				"CH",
				"CI",
				"CL",
				"CM",
				"CO",
				"CR",
				"CV",
				"CW",
				"CY",
				"CZ",
				"DE",
				"DJ",
				"DK",
				"DM",
				"DO",
				"DZ",
				"EC",
				"EE",
				"EG",
				"ES",
				"FI",
				"FJ",
				"FM",
				"FR",
				"GA",
				"GB",
				"GD",
				"GE",
				"GH",
				"GM",
				"GN",
				"GQ",
				"GR",
				"GT",
				"GW",
				"GY",
				"HK",
				"HN",
				"HR",
				"HT",
				"HU",
				"ID",
				"IL",
				"IN",
				"IS",
				"IT",
				"JM",
				"JO",
				"JP",
				"KE",
				"KG",
				"KH",
				"KI",
				"KM",
				"KN",
				"KR",
				"KW",
				"KZ",
				"LA",
				"LB",
				"LC",
				"LI",
				"LK",
				"LR",
				"LS",
				"LT",
				"LU",
				"LV",
				"MA",
				"MC",
				"MD",
				"ME",
				"MG",
				"MH",
				"MK",
				"ML",
				"MN",
				"MO",
				"MR",
				"MT",
				"MU",
				"MV",
				"MW",
				"MX",
				"MY",
				"MZ",
				"NA",
				"NE",
				"NG",
				"NI",
				"NL",
				"NO",
				"NP",
				"NR",
				"NZ",
				"OM",
				"PA",
				"PE",
				"PG",
				"PH",
				"PK",
				"PL",
				"PS",
				"PT",
				"PW",
				"PY",
				"QA",
				"RO",
				"RS",
				"RU",
				"RW",
				"SA",
				"SB",
				"SC",
				"SE",
				"SG",
				"SI",
				"SK",
				"SL",
				"SM",
				"SN",
				"SR",
				"ST",
				"SV",
				"SZ",
				"TD",
				"TG",
				"TH",
				"TL",
				"TN",
				"TO",
				"TR",
				"TT",
				"TV",
				"TW",
				"TZ",
				"UA",
				"UG",
				"UY",
				"UZ",
				"VC",
				"VN",
				"VU",
				"WS",
				"XK",
				"ZA",
				"ZM",
				"ZW"
			  ],
			  "external_urls": {
				"spotify": "https://open.spotify.com/album/4TMMcbyi7mC5aJeOvTn6FW"
			  },
			  "href": "https://api.spotify.com/v1/albums/4TMMcbyi7mC5aJeOvTn6FW",
			  "id": "4TMMcbyi7mC5aJeOvTn6FW",
			  "images": [
				{
				  "height": 640,
				  "url": "https://i.scdn.co/image/ab67616d0000b2738cc0052d073a61b39d30f54a",
				  "width": 640
				},
				{
				  "height": 300,
				  "url": "https://i.scdn.co/image/ab67616d00001e028cc0052d073a61b39d30f54a",
				  "width": 300
				},
				{
				  "height": 64,
				  "url": "https://i.scdn.co/image/ab67616d000048518cc0052d073a61b39d30f54a",
				  "width": 64
				}
			  ],
			  "name": "The Blower's Daughter",
			  "release_date": "2002",
			  "release_date_precision": "year",
			  "total_tracks": 2,
			  "type": "album",
			  "uri": "spotify:album:4TMMcbyi7mC5aJeOvTn6FW"
			},
			"artists": [
			  {
				"external_urls": {
				  "spotify": "https://open.spotify.com/artist/14r9dR01KeBLFfylVSKCZQ"
				},
				"href": "https://api.spotify.com/v1/artists/14r9dR01KeBLFfylVSKCZQ",
				"id": "14r9dR01KeBLFfylVSKCZQ",
				"name": "Damien Rice",
				"type": "artist",
				"uri": "spotify:artist:14r9dR01KeBLFfylVSKCZQ"
			  }
			],
			"available_markets": [
			  "AD",
			  "AE",
			  "AG",
			  "AL",
			  "AM",
			  "AO",
			  "AR",
			  "AT",
			  "AU",
			  "AZ",
			  "BA",
			  "BB",
			  "BD",
			  "BE",
			  "BF",
			  "BG",
			  "BH",
			  "BI",
			  "BJ",
			  "BN",
			  "BO",
			  "BR",
			  "BS",
			  "BT",
			  "BW",
			  "BY",
			  "BZ",
			  "CH",
			  "CI",
			  "CL",
			  "CM",
			  "CO",
			  "CR",
			  "CV",
			  "CW",
			  "CY",
			  "CZ",
			  "DE",
			  "DJ",
			  "DK",
			  "DM",
			  "DO",
			  "DZ",
			  "EC",
			  "EE",
			  "EG",
			  "ES",
			  "FI",
			  "FJ",
			  "FM",
			  "FR",
			  "GA",
			  "GB",
			  "GD",
			  "GE",
			  "GH",
			  "GM",
			  "GN",
			  "GQ",
			  "GR",
			  "GT",
			  "GW",
			  "GY",
			  "HK",
			  "HN",
			  "HR",
			  "HT",
			  "HU",
			  "ID",
			  "IL",
			  "IN",
			  "IS",
			  "IT",
			  "JM",
			  "JO",
			  "JP",
			  "KE",
			  "KG",
			  "KH",
			  "KI",
			  "KM",
			  "KN",
			  "KR",
			  "KW",
			  "KZ",
			  "LA",
			  "LB",
			  "LC",
			  "LI",
			  "LK",
			  "LR",
			  "LS",
			  "LT",
			  "LU",
			  "LV",
			  "MA",
			  "MC",
			  "MD",
			  "ME",
			  "MG",
			  "MH",
			  "MK",
			  "ML",
			  "MN",
			  "MO",
			  "MR",
			  "MT",
			  "MU",
			  "MV",
			  "MW",
			  "MX",
			  "MY",
			  "MZ",
			  "NA",
			  "NE",
			  "NG",
			  "NI",
			  "NL",
			  "NO",
			  "NP",
			  "NR",
			  "NZ",
			  "OM",
			  "PA",
			  "PE",
			  "PG",
			  "PH",
			  "PK",
			  "PL",
			  "PS",
			  "PT",
			  "PW",
			  "PY",
			  "QA",
			  "RO",
			  "RS",
			  "RU",
			  "RW",
			  "SA",
			  "SB",
			  "SC",
			  "SE",
			  "SG",
			  "SI",
			  "SK",
			  "SL",
			  "SM",
			  "SN",
			  "SR",
			  "ST",
			  "SV",
			  "SZ",
			  "TD",
			  "TG",
			  "TH",
			  "TL",
			  "TN",
			  "TO",
			  "TR",
			  "TT",
			  "TV",
			  "TW",
			  "TZ",
			  "UA",
			  "UG",
			  "UY",
			  "UZ",
			  "VC",
			  "VN",
			  "VU",
			  "WS",
			  "XK",
			  "ZA",
			  "ZM",
			  "ZW"
			],
			"disc_number": 1,
			"duration_ms": 288466,
			"explicit": false,
			"external_ids": {
			  "isrc": "IEABD0100003"
			},
			"external_urls": {
			  "spotify": "https://open.spotify.com/track/7tdXvaCZmWZJOrZE9zFXpr"
			},
			"href": "https://api.spotify.com/v1/tracks/7tdXvaCZmWZJOrZE9zFXpr",
			"id": "7tdXvaCZmWZJOrZE9zFXpr",
			"is_local": false,
			"name": "The Blower's Daughter",
			"popularity": 49,
			"preview_url": "https://p.scdn.co/mp3-preview/0c1b3c3ec482a2285331fdcd911d0bb6300e5963?cid=db8c415a273c4ffc9286e12ff24b8b9f",
			"track_number": 1,
			"type": "track",
			"uri": "spotify:track:7tdXvaCZmWZJOrZE9zFXpr"
		  },
		  {
			"album": {
			  "album_type": "ALBUM",
			  "artists": [
				{
				  "external_urls": {
					"spotify": "https://open.spotify.com/artist/0qT79UgT5tY4yudH9VfsdT"
				  },
				  "href": "https://api.spotify.com/v1/artists/0qT79UgT5tY4yudH9VfsdT",
				  "id": "0qT79UgT5tY4yudH9VfsdT",
				  "name": "Sum 41",
				  "type": "artist",
				  "uri": "spotify:artist:0qT79UgT5tY4yudH9VfsdT"
				}
			  ],
			  "available_markets": [
			  ],
			  "external_urls": {
				"spotify": "https://open.spotify.com/album/6QNltz3Yi7UuVt7jQhqinC"
			  },
			  "href": "https://api.spotify.com/v1/albums/6QNltz3Yi7UuVt7jQhqinC",
			  "id": "6QNltz3Yi7UuVt7jQhqinC",
			  "images": [
				{
				  "height": 640,
				  "url": "https://i.scdn.co/image/ab67616d0000b27366b22a2e1f6490753df5096a",
				  "width": 640
				},
				{
				  "height": 300,
				  "url": "https://i.scdn.co/image/ab67616d00001e0266b22a2e1f6490753df5096a",
				  "width": 300
				},
				{
				  "height": 64,
				  "url": "https://i.scdn.co/image/ab67616d0000485166b22a2e1f6490753df5096a",
				  "width": 64
				}
			  ],
			  "name": "Underclass Hero",
			  "release_date": "2007-01-01",
			  "release_date_precision": "day",
			  "total_tracks": 14,
			  "type": "album",
			  "uri": "spotify:album:6QNltz3Yi7UuVt7jQhqinC"
			},
			"artists": [
			  {
				"external_urls": {
				  "spotify": "https://open.spotify.com/artist/0qT79UgT5tY4yudH9VfsdT"
				},
				"href": "https://api.spotify.com/v1/artists/0qT79UgT5tY4yudH9VfsdT",
				"id": "0qT79UgT5tY4yudH9VfsdT",
				"name": "Sum 41",
				"type": "artist",
				"uri": "spotify:artist:0qT79UgT5tY4yudH9VfsdT"
			  }
			],
			"available_markets": [
			],
			"disc_number": 1,
			"duration_ms": 291360,
			"explicit": false,
			"external_ids": {
			  "isrc": "USUM70740344"
			},
			"external_urls": {
			  "spotify": "https://open.spotify.com/track/7JcB1XSpmlULBSvnEis6Fc"
			},
			"href": "https://api.spotify.com/v1/tracks/7JcB1XSpmlULBSvnEis6Fc",
			"id": "7JcB1XSpmlULBSvnEis6Fc",
			"is_local": false,
			"name": "With Me",
			"popularity": 0,
			"preview_url": null,
			"track_number": 9,
			"type": "track",
			"uri": "spotify:track:7JcB1XSpmlULBSvnEis6Fc"
		  },
		  {
			"album": {
			  "album_type": "ALBUM",
			  "artists": [
				{
				  "external_urls": {
					"spotify": "https://open.spotify.com/artist/7rXo5QTwwFBYZ5Z3veUVg8"
				  },
				  "href": "https://api.spotify.com/v1/artists/7rXo5QTwwFBYZ5Z3veUVg8",
				  "id": "7rXo5QTwwFBYZ5Z3veUVg8",
				  "name": "Texas Is The Reason",
				  "type": "artist",
				  "uri": "spotify:artist:7rXo5QTwwFBYZ5Z3veUVg8"
				}
			  ],
			  "available_markets": [
				"AD",
				"AE",
				"AG",
				"AL",
				"AM",
				"AO",
				"AR",
				"AT",
				"AU",
				"AZ",
				"BA",
				"BB",
				"BD",
				"BE",
				"BF",
				"BG",
				"BH",
				"BI",
				"BJ",
				"BN",
				"BO",
				"BR",
				"BS",
				"BT",
				"BW",
				"BY",
				"BZ",
				"CA",
				"CH",
				"CI",
				"CL",
				"CM",
				"CO",
				"CR",
				"CV",
				"CY",
				"CZ",
				"DE",
				"DJ",
				"DK",
				"DM",
				"DO",
				"DZ",
				"EC",
				"EE",
				"EG",
				"ES",
				"FI",
				"FJ",
				"FM",
				"FR",
				"GA",
				"GB",
				"GD",
				"GE",
				"GH",
				"GM",
				"GN",
				"GQ",
				"GR",
				"GT",
				"GW",
				"GY",
				"HK",
				"HN",
				"HR",
				"HT",
				"HU",
				"ID",
				"IE",
				"IL",
				"IN",
				"IS",
				"IT",
				"JM",
				"JO",
				"KE",
				"KG",
				"KH",
				"KI",
				"KM",
				"KN",
				"KR",
				"KW",
				"KZ",
				"LA",
				"LB",
				"LC",
				"LI",
				"LK",
				"LR",
				"LS",
				"LT",
				"LU",
				"LV",
				"MA",
				"MC",
				"MD",
				"MG",
				"MH",
				"MK",
				"ML",
				"MN",
				"MO",
				"MR",
				"MT",
				"MU",
				"MV",
				"MW",
				"MX",
				"MY",
				"MZ",
				"NA",
				"NE",
				"NG",
				"NI",
				"NL",
				"NO",
				"NP",
				"NR",
				"NZ",
				"OM",
				"PA",
				"PE",
				"PG",
				"PH",
				"PK",
				"PL",
				"PS",
				"PT",
				"PW",
				"PY",
				"QA",
				"RO",
				"RU",
				"RW",
				"SA",
				"SB",
				"SC",
				"SE",
				"SG",
				"SI",
				"SK",
				"SL",
				"SM",
				"SN",
				"SR",
				"ST",
				"SV",
				"SZ",
				"TD",
				"TG",
				"TH",
				"TL",
				"TN",
				"TO",
				"TR",
				"TT",
				"TV",
				"TW",
				"TZ",
				"UA",
				"UG",
				"US",
				"UY",
				"UZ",
				"VC",
				"VN",
				"VU",
				"WS",
				"ZA",
				"ZM",
				"ZW"
			  ],
			  "external_urls": {
				"spotify": "https://open.spotify.com/album/3NXykL2XzIRmMEiMKjTkN7"
			  },
			  "href": "https://api.spotify.com/v1/albums/3NXykL2XzIRmMEiMKjTkN7",
			  "id": "3NXykL2XzIRmMEiMKjTkN7",
			  "images": [
				{
				  "height": 640,
				  "url": "https://i.scdn.co/image/ab67616d0000b273198d3379f0eb1599fc6a5da1",
				  "width": 640
				},
				{
				  "height": 300,
				  "url": "https://i.scdn.co/image/ab67616d00001e02198d3379f0eb1599fc6a5da1",
				  "width": 300
				},
				{
				  "height": 64,
				  "url": "https://i.scdn.co/image/ab67616d00004851198d3379f0eb1599fc6a5da1",
				  "width": 64
				}
			  ],
			  "name": "Do You Know Who You Are?: The Complete Collection",
			  "release_date": "2013-02-12",
			  "release_date_precision": "day",
			  "total_tracks": 16,
			  "type": "album",
			  "uri": "spotify:album:3NXykL2XzIRmMEiMKjTkN7"
			},
			"artists": [
			  {
				"external_urls": {
				  "spotify": "https://open.spotify.com/artist/7rXo5QTwwFBYZ5Z3veUVg8"
				},
				"href": "https://api.spotify.com/v1/artists/7rXo5QTwwFBYZ5Z3veUVg8",
				"id": "7rXo5QTwwFBYZ5Z3veUVg8",
				"name": "Texas Is The Reason",
				"type": "artist",
				"uri": "spotify:artist:7rXo5QTwwFBYZ5Z3veUVg8"
			  }
			],
			"available_markets": [
			  "AD",
			  "AE",
			  "AG",
			  "AL",
			  "AM",
			  "AO",
			  "AR",
			  "AT",
			  "AU",
			  "AZ",
			  "BA",
			  "BB",
			  "BD",
			  "BE",
			  "BF",
			  "BG",
			  "BH",
			  "BI",
			  "BJ",
			  "BN",
			  "BO",
			  "BR",
			  "BS",
			  "BT",
			  "BW",
			  "BY",
			  "BZ",
			  "CA",
			  "CH",
			  "CI",
			  "CL",
			  "CM",
			  "CO",
			  "CR",
			  "CV",
			  "CY",
			  "CZ",
			  "DE",
			  "DJ",
			  "DK",
			  "DM",
			  "DO",
			  "DZ",
			  "EC",
			  "EE",
			  "EG",
			  "ES",
			  "FI",
			  "FJ",
			  "FM",
			  "FR",
			  "GA",
			  "GB",
			  "GD",
			  "GE",
			  "GH",
			  "GM",
			  "GN",
			  "GQ",
			  "GR",
			  "GT",
			  "GW",
			  "GY",
			  "HK",
			  "HN",
			  "HR",
			  "HT",
			  "HU",
			  "ID",
			  "IE",
			  "IL",
			  "IN",
			  "IS",
			  "IT",
			  "JM",
			  "JO",
			  "KE",
			  "KG",
			  "KH",
			  "KI",
			  "KM",
			  "KN",
			  "KR",
			  "KW",
			  "KZ",
			  "LA",
			  "LB",
			  "LC",
			  "LI",
			  "LK",
			  "LR",
			  "LS",
			  "LT",
			  "LU",
			  "LV",
			  "MA",
			  "MC",
			  "MD",
			  "MG",
			  "MH",
			  "MK",
			  "ML",
			  "MN",
			  "MO",
			  "MR",
			  "MT",
			  "MU",
			  "MV",
			  "MW",
			  "MX",
			  "MY",
			  "MZ",
			  "NA",
			  "NE",
			  "NG",
			  "NI",
			  "NL",
			  "NO",
			  "NP",
			  "NR",
			  "NZ",
			  "OM",
			  "PA",
			  "PE",
			  "PG",
			  "PH",
			  "PK",
			  "PL",
			  "PS",
			  "PT",
			  "PW",
			  "PY",
			  "QA",
			  "RO",
			  "RU",
			  "RW",
			  "SA",
			  "SB",
			  "SC",
			  "SE",
			  "SG",
			  "SI",
			  "SK",
			  "SL",
			  "SM",
			  "SN",
			  "SR",
			  "ST",
			  "SV",
			  "SZ",
			  "TD",
			  "TG",
			  "TH",
			  "TL",
			  "TN",
			  "TO",
			  "TR",
			  "TT",
			  "TV",
			  "TW",
			  "TZ",
			  "UA",
			  "UG",
			  "US",
			  "UY",
			  "UZ",
			  "VC",
			  "VN",
			  "VU",
			  "WS",
			  "ZA",
			  "ZM",
			  "ZW"
			],
			"disc_number": 1,
			"duration_ms": 145773,
			"explicit": false,
			"external_ids": {
			  "isrc": "USB4U1315114"
			},
			"external_urls": {
			  "spotify": "https://open.spotify.com/track/2ymt2b4x03JKFOIJj7YtDr"
			},
			"href": "https://api.spotify.com/v1/tracks/2ymt2b4x03JKFOIJj7YtDr",
			"id": "2ymt2b4x03JKFOIJj7YtDr",
			"is_local": false,
			"name": "If It's Here When We Get Back It's Ours",
			"popularity": 23,
			"preview_url": "https://p.scdn.co/mp3-preview/b0cfbef3db5c516ba1105d4b988568bd030617c2?cid=db8c415a273c4ffc9286e12ff24b8b9f",
			"track_number": 14,
			"type": "track",
			"uri": "spotify:track:2ymt2b4x03JKFOIJj7YtDr"
		  },
		  {
			"album": {
			  "album_type": "ALBUM",
			  "artists": [
				{
				  "external_urls": {
					"spotify": "https://open.spotify.com/artist/3WfJ1OtrWI7RViX9DMyEGy"
				  },
				  "href": "https://api.spotify.com/v1/artists/3WfJ1OtrWI7RViX9DMyEGy",
				  "id": "3WfJ1OtrWI7RViX9DMyEGy",
				  "name": "Mayday Parade",
				  "type": "artist",
				  "uri": "spotify:artist:3WfJ1OtrWI7RViX9DMyEGy"
				}
			  ],
			  "available_markets": [
			  ],
			  "external_urls": {
				"spotify": "https://open.spotify.com/album/5hV1HRTgfWc0PlSQbFHxYH"
			  },
			  "href": "https://api.spotify.com/v1/albums/5hV1HRTgfWc0PlSQbFHxYH",
			  "id": "5hV1HRTgfWc0PlSQbFHxYH",
			  "images": [
				{
				  "height": 640,
				  "url": "https://i.scdn.co/image/ab67616d0000b273c7b43c63c3fedee0c318f4a9",
				  "width": 640
				},
				{
				  "height": 300,
				  "url": "https://i.scdn.co/image/ab67616d00001e02c7b43c63c3fedee0c318f4a9",
				  "width": 300
				},
				{
				  "height": 64,
				  "url": "https://i.scdn.co/image/ab67616d00004851c7b43c63c3fedee0c318f4a9",
				  "width": 64
				}
			  ],
			  "name": "A Lesson In Romantics",
			  "release_date": "2007-07-10",
			  "release_date_precision": "day",
			  "total_tracks": 12,
			  "type": "album",
			  "uri": "spotify:album:5hV1HRTgfWc0PlSQbFHxYH"
			},
			"artists": [
			  {
				"external_urls": {
				  "spotify": "https://open.spotify.com/artist/3WfJ1OtrWI7RViX9DMyEGy"
				},
				"href": "https://api.spotify.com/v1/artists/3WfJ1OtrWI7RViX9DMyEGy",
				"id": "3WfJ1OtrWI7RViX9DMyEGy",
				"name": "Mayday Parade",
				"type": "artist",
				"uri": "spotify:artist:3WfJ1OtrWI7RViX9DMyEGy"
			  }
			],
			"available_markets": [
			],
			"disc_number": 1,
			"duration_ms": 241426,
			"explicit": false,
			"external_ids": {
			  "isrc": "US5260709909"
			},
			"external_urls": {
			  "spotify": "https://open.spotify.com/track/072GjxVG15H5cGBGZJCssU"
			},
			"href": "https://api.spotify.com/v1/tracks/072GjxVG15H5cGBGZJCssU",
			"id": "072GjxVG15H5cGBGZJCssU",
			"is_local": false,
			"name": "I'd Hate To Be You When People Find Out What This Song Is About",
			"popularity": 0,
			"preview_url": null,
			"track_number": 9,
			"type": "track",
			"uri": "spotify:track:072GjxVG15H5cGBGZJCssU"
		  },
		  {
			"album": {
			  "album_type": "ALBUM",
			  "artists": [
				{
				  "external_urls": {
					"spotify": "https://open.spotify.com/artist/4ZIBrskTJWmkJUvM7uAu1o"
				  },
				  "href": "https://api.spotify.com/v1/artists/4ZIBrskTJWmkJUvM7uAu1o",
				  "id": "4ZIBrskTJWmkJUvM7uAu1o",
				  "name": "Chiodos",
				  "type": "artist",
				  "uri": "spotify:artist:4ZIBrskTJWmkJUvM7uAu1o"
				}
			  ],
			  "available_markets": [
				"AD",
				"AE",
				"AG",
				"AL",
				"AM",
				"AO",
				"AR",
				"AT",
				"AU",
				"AZ",
				"BA",
				"BB",
				"BD",
				"BE",
				"BF",
				"BG",
				"BH",
				"BI",
				"BJ",
				"BN",
				"BO",
				"BR",
				"BS",
				"BT",
				"BW",
				"BY",
				"BZ",
				"CA",
				"CH",
				"CI",
				"CL",
				"CM",
				"CO",
				"CR",
				"CV",
				"CY",
				"CZ",
				"DE",
				"DJ",
				"DK",
				"DM",
				"DO",
				"DZ",
				"EC",
				"EE",
				"EG",
				"ES",
				"FI",
				"FJ",
				"FM",
				"FR",
				"GA",
				"GB",
				"GD",
				"GE",
				"GH",
				"GM",
				"GN",
				"GQ",
				"GR",
				"GT",
				"GW",
				"GY",
				"HK",
				"HN",
				"HR",
				"HT",
				"HU",
				"ID",
				"IE",
				"IL",
				"IN",
				"IS",
				"IT",
				"JM",
				"JO",
				"JP",
				"KE",
				"KG",
				"KH",
				"KI",
				"KM",
				"KN",
				"KR",
				"KW",
				"KZ",
				"LA",
				"LB",
				"LC",
				"LI",
				"LK",
				"LR",
				"LS",
				"LT",
				"LU",
				"LV",
				"MA",
				"MC",
				"MD",
				"ME",
				"MG",
				"MH",
				"MK",
				"ML",
				"MN",
				"MO",
				"MR",
				"MT",
				"MU",
				"MV",
				"MW",
				"MX",
				"MY",
				"MZ",
				"NA",
				"NE",
				"NG",
				"NI",
				"NL",
				"NO",
				"NP",
				"NR",
				"NZ",
				"OM",
				"PA",
				"PE",
				"PG",
				"PH",
				"PK",
				"PL",
				"PS",
				"PT",
				"PW",
				"PY",
				"QA",
				"RO",
				"RS",
				"RU",
				"RW",
				"SA",
				"SB",
				"SC",
				"SE",
				"SG",
				"SI",
				"SK",
				"SL",
				"SM",
				"SN",
				"SR",
				"ST",
				"SV",
				"SZ",
				"TD",
				"TG",
				"TH",
				"TL",
				"TN",
				"TO",
				"TR",
				"TT",
				"TV",
				"TW",
				"TZ",
				"UA",
				"UG",
				"US",
				"UY",
				"UZ",
				"VC",
				"VN",
				"VU",
				"WS",
				"XK",
				"ZA",
				"ZM",
				"ZW"
			  ],
			  "external_urls": {
				"spotify": "https://open.spotify.com/album/0OEsBt4DiKAGACbzmhwbaS"
			  },
			  "href": "https://api.spotify.com/v1/albums/0OEsBt4DiKAGACbzmhwbaS",
			  "id": "0OEsBt4DiKAGACbzmhwbaS",
			  "images": [
				{
				  "height": 640,
				  "url": "https://i.scdn.co/image/ab67616d0000b273565a166b9f44fc0250f5769e",
				  "width": 640
				},
				{
				  "height": 300,
				  "url": "https://i.scdn.co/image/ab67616d00001e02565a166b9f44fc0250f5769e",
				  "width": 300
				},
				{
				  "height": 64,
				  "url": "https://i.scdn.co/image/ab67616d00004851565a166b9f44fc0250f5769e",
				  "width": 64
				}
			  ],
			  "name": "All's Well That Ends Well",
			  "release_date": "2005",
			  "release_date_precision": "year",
			  "total_tracks": 13,
			  "type": "album",
			  "uri": "spotify:album:0OEsBt4DiKAGACbzmhwbaS"
			},
			"artists": [
			  {
				"external_urls": {
				  "spotify": "https://open.spotify.com/artist/4ZIBrskTJWmkJUvM7uAu1o"
				},
				"href": "https://api.spotify.com/v1/artists/4ZIBrskTJWmkJUvM7uAu1o",
				"id": "4ZIBrskTJWmkJUvM7uAu1o",
				"name": "Chiodos",
				"type": "artist",
				"uri": "spotify:artist:4ZIBrskTJWmkJUvM7uAu1o"
			  }
			],
			"available_markets": [
			  "AD",
			  "AE",
			  "AG",
			  "AL",
			  "AM",
			  "AO",
			  "AR",
			  "AT",
			  "AU",
			  "AZ",
			  "BA",
			  "BB",
			  "BD",
			  "BE",
			  "BF",
			  "BG",
			  "BH",
			  "BI",
			  "BJ",
			  "BN",
			  "BO",
			  "BR",
			  "BS",
			  "BT",
			  "BW",
			  "BY",
			  "BZ",
			  "CA",
			  "CH",
			  "CI",
			  "CL",
			  "CM",
			  "CO",
			  "CR",
			  "CV",
			  "CY",
			  "CZ",
			  "DE",
			  "DJ",
			  "DK",
			  "DM",
			  "DO",
			  "DZ",
			  "EC",
			  "EE",
			  "EG",
			  "ES",
			  "FI",
			  "FJ",
			  "FM",
			  "FR",
			  "GA",
			  "GB",
			  "GD",
			  "GE",
			  "GH",
			  "GM",
			  "GN",
			  "GQ",
			  "GR",
			  "GT",
			  "GW",
			  "GY",
			  "HK",
			  "HN",
			  "HR",
			  "HT",
			  "HU",
			  "ID",
			  "IE",
			  "IL",
			  "IN",
			  "IS",
			  "IT",
			  "JM",
			  "JO",
			  "JP",
			  "KE",
			  "KG",
			  "KH",
			  "KI",
			  "KM",
			  "KN",
			  "KR",
			  "KW",
			  "KZ",
			  "LA",
			  "LB",
			  "LC",
			  "LI",
			  "LK",
			  "LR",
			  "LS",
			  "LT",
			  "LU",
			  "LV",
			  "MA",
			  "MC",
			  "MD",
			  "ME",
			  "MG",
			  "MH",
			  "MK",
			  "ML",
			  "MN",
			  "MO",
			  "MR",
			  "MT",
			  "MU",
			  "MV",
			  "MW",
			  "MX",
			  "MY",
			  "MZ",
			  "NA",
			  "NE",
			  "NG",
			  "NI",
			  "NL",
			  "NO",
			  "NP",
			  "NR",
			  "NZ",
			  "OM",
			  "PA",
			  "PE",
			  "PG",
			  "PH",
			  "PK",
			  "PL",
			  "PS",
			  "PT",
			  "PW",
			  "PY",
			  "QA",
			  "RO",
			  "RS",
			  "RU",
			  "RW",
			  "SA",
			  "SB",
			  "SC",
			  "SE",
			  "SG",
			  "SI",
			  "SK",
			  "SL",
			  "SM",
			  "SN",
			  "SR",
			  "ST",
			  "SV",
			  "SZ",
			  "TD",
			  "TG",
			  "TH",
			  "TL",
			  "TN",
			  "TO",
			  "TR",
			  "TT",
			  "TV",
			  "TW",
			  "TZ",
			  "UA",
			  "UG",
			  "US",
			  "UY",
			  "UZ",
			  "VC",
			  "VN",
			  "VU",
			  "WS",
			  "XK",
			  "ZA",
			  "ZM",
			  "ZW"
			],
			"disc_number": 1,
			"duration_ms": 216293,
			"explicit": false,
			"external_ids": {
			  "isrc": "US3X50511106"
			},
			"external_urls": {
			  "spotify": "https://open.spotify.com/track/6GKhlcZeyEW9Y5ZLZ37HZ3"
			},
			"href": "https://api.spotify.com/v1/tracks/6GKhlcZeyEW9Y5ZLZ37HZ3",
			"id": "6GKhlcZeyEW9Y5ZLZ37HZ3",
			"is_local": false,
			"name": "The Words \"Best Friend\" Become Redefined",
			"popularity": 52,
			"preview_url": "https://p.scdn.co/mp3-preview/574c62a048f1761d5aa654de8212dbc1678b4bf8?cid=db8c415a273c4ffc9286e12ff24b8b9f",
			"track_number": 6,
			"type": "track",
			"uri": "spotify:track:6GKhlcZeyEW9Y5ZLZ37HZ3"
		  },
		  {
			"album": {
			  "album_type": "ALBUM",
			  "artists": [
				{
				  "external_urls": {
					"spotify": "https://open.spotify.com/artist/24XtlMhEMNdi822vi0MhY1"
				  },
				  "href": "https://api.spotify.com/v1/artists/24XtlMhEMNdi822vi0MhY1",
				  "id": "24XtlMhEMNdi822vi0MhY1",
				  "name": "Taking Back Sunday",
				  "type": "artist",
				  "uri": "spotify:artist:24XtlMhEMNdi822vi0MhY1"
				}
			  ],
			  "available_markets": [
			  ],
			  "external_urls": {
				"spotify": "https://open.spotify.com/album/6OWxP59cOtitg0ALmbms8e"
			  },
			  "href": "https://api.spotify.com/v1/albums/6OWxP59cOtitg0ALmbms8e",
			  "id": "6OWxP59cOtitg0ALmbms8e",
			  "images": [
				{
				  "height": 640,
				  "url": "https://i.scdn.co/image/ab67616d0000b27300b1ad0727b1682a892d923f",
				  "width": 640
				},
				{
				  "height": 300,
				  "url": "https://i.scdn.co/image/ab67616d00001e0200b1ad0727b1682a892d923f",
				  "width": 300
				},
				{
				  "height": 64,
				  "url": "https://i.scdn.co/image/ab67616d0000485100b1ad0727b1682a892d923f",
				  "width": 64
				}
			  ],
			  "name": "Tell All Your Friends (Re-Issue)",
			  "release_date": "2002",
			  "release_date_precision": "year",
			  "total_tracks": 12,
			  "type": "album",
			  "uri": "spotify:album:6OWxP59cOtitg0ALmbms8e"
			},
			"artists": [
			  {
				"external_urls": {
				  "spotify": "https://open.spotify.com/artist/24XtlMhEMNdi822vi0MhY1"
				},
				"href": "https://api.spotify.com/v1/artists/24XtlMhEMNdi822vi0MhY1",
				"id": "24XtlMhEMNdi822vi0MhY1",
				"name": "Taking Back Sunday",
				"type": "artist",
				"uri": "spotify:artist:24XtlMhEMNdi822vi0MhY1"
			  }
			],
			"available_markets": [
			],
			"disc_number": 1,
			"duration_ms": 184000,
			"explicit": false,
			"external_ids": {
			  "isrc": "USVIC0528610"
			},
			"external_urls": {
			  "spotify": "https://open.spotify.com/track/0ntevstXQoNDIZkslinqdy"
			},
			"href": "https://api.spotify.com/v1/tracks/0ntevstXQoNDIZkslinqdy",
			"id": "0ntevstXQoNDIZkslinqdy",
			"is_local": false,
			"name": "Head Club",
			"popularity": 0,
			"preview_url": null,
			"track_number": 10,
			"type": "track",
			"uri": "spotify:track:0ntevstXQoNDIZkslinqdy"
		  },
		  {
			"album": {
			  "album_type": "ALBUM",
			  "artists": [
				{
				  "external_urls": {
					"spotify": "https://open.spotify.com/artist/168dgYui7ExaU612eooDF1"
				  },
				  "href": "https://api.spotify.com/v1/artists/168dgYui7ExaU612eooDF1",
				  "id": "168dgYui7ExaU612eooDF1",
				  "name": "Brand New",
				  "type": "artist",
				  "uri": "spotify:artist:168dgYui7ExaU612eooDF1"
				}
			  ],
			  "available_markets": [
				"CA",
				"MX"
			  ],
			  "external_urls": {
				"spotify": "https://open.spotify.com/album/2BRqfk8jL7y3egZqlc5MkU"
			  },
			  "href": "https://api.spotify.com/v1/albums/2BRqfk8jL7y3egZqlc5MkU",
			  "id": "2BRqfk8jL7y3egZqlc5MkU",
			  "images": [
				{
				  "height": 640,
				  "url": "https://i.scdn.co/image/ab67616d0000b273a61b46c287bdb447967a752e",
				  "width": 640
				},
				{
				  "height": 300,
				  "url": "https://i.scdn.co/image/ab67616d00001e02a61b46c287bdb447967a752e",
				  "width": 300
				},
				{
				  "height": 64,
				  "url": "https://i.scdn.co/image/ab67616d00004851a61b46c287bdb447967a752e",
				  "width": 64
				}
			  ],
			  "name": "The Devil And God Are Raging Inside Me",
			  "release_date": "2006-01-01",
			  "release_date_precision": "day",
			  "total_tracks": 12,
			  "type": "album",
			  "uri": "spotify:album:2BRqfk8jL7y3egZqlc5MkU"
			},
			"artists": [
			  {
				"external_urls": {
				  "spotify": "https://open.spotify.com/artist/168dgYui7ExaU612eooDF1"
				},
				"href": "https://api.spotify.com/v1/artists/168dgYui7ExaU612eooDF1",
				"id": "168dgYui7ExaU612eooDF1",
				"name": "Brand New",
				"type": "artist",
				"uri": "spotify:artist:168dgYui7ExaU612eooDF1"
			  }
			],
			"available_markets": [
			  "CA",
			  "MX"
			],
			"disc_number": 1,
			"duration_ms": 124106,
			"explicit": false,
			"external_ids": {
			  "isrc": "USUM70614456"
			},
			"external_urls": {
			  "spotify": "https://open.spotify.com/track/0IGG4kreIr85kHHaaIp3q0"
			},
			"href": "https://api.spotify.com/v1/tracks/0IGG4kreIr85kHHaaIp3q0",
			"id": "0IGG4kreIr85kHHaaIp3q0",
			"is_local": false,
			"name": "Untitled",
			"popularity": 19,
			"preview_url": null,
			"track_number": 10,
			"type": "track",
			"uri": "spotify:track:0IGG4kreIr85kHHaaIp3q0"
		  },
		  {
			"album": {
			  "album_type": "SINGLE",
			  "artists": [
				{
				  "external_urls": {
					"spotify": "https://open.spotify.com/artist/0nmQIMXWTXfhgOBdNzhGOs"
				  },
				  "href": "https://api.spotify.com/v1/artists/0nmQIMXWTXfhgOBdNzhGOs",
				  "id": "0nmQIMXWTXfhgOBdNzhGOs",
				  "name": "Avenged Sevenfold",
				  "type": "artist",
				  "uri": "spotify:artist:0nmQIMXWTXfhgOBdNzhGOs"
				}
			  ],
			  "available_markets": [
			  ],
			  "external_urls": {
				"spotify": "https://open.spotify.com/album/5Kuyk9hoK7HKVfSD0WOD42"
			  },
			  "href": "https://api.spotify.com/v1/albums/5Kuyk9hoK7HKVfSD0WOD42",
			  "id": "5Kuyk9hoK7HKVfSD0WOD42",
			  "images": [
				{
				  "height": 640,
				  "url": "https://i.scdn.co/image/ab67616d0000b2733ab7e297f6541d0636d8d28b",
				  "width": 640
				},
				{
				  "height": 300,
				  "url": "https://i.scdn.co/image/ab67616d00001e023ab7e297f6541d0636d8d28b",
				  "width": 300
				},
				{
				  "height": 64,
				  "url": "https://i.scdn.co/image/ab67616d000048513ab7e297f6541d0636d8d28b",
				  "width": 64
				}
			  ],
			  "name": "Afterlife (U.K. 1-Track DMD)",
			  "release_date": "2007-12-09",
			  "release_date_precision": "day",
			  "total_tracks": 1,
			  "type": "album",
			  "uri": "spotify:album:5Kuyk9hoK7HKVfSD0WOD42"
			},
			"artists": [
			  {
				"external_urls": {
				  "spotify": "https://open.spotify.com/artist/0nmQIMXWTXfhgOBdNzhGOs"
				},
				"href": "https://api.spotify.com/v1/artists/0nmQIMXWTXfhgOBdNzhGOs",
				"id": "0nmQIMXWTXfhgOBdNzhGOs",
				"name": "Avenged Sevenfold",
				"type": "artist",
				"uri": "spotify:artist:0nmQIMXWTXfhgOBdNzhGOs"
			  }
			],
			"available_markets": [
			],
			"disc_number": 1,
			"duration_ms": 351560,
			"explicit": false,
			"external_ids": {
			  "isrc": "USWB10703995"
			},
			"external_urls": {
			  "spotify": "https://open.spotify.com/track/4geHi4niVBx4lQ4Nku1Q3t"
			},
			"href": "https://api.spotify.com/v1/tracks/4geHi4niVBx4lQ4Nku1Q3t",
			"id": "4geHi4niVBx4lQ4Nku1Q3t",
			"is_local": false,
			"name": "Afterlife",
			"popularity": 0,
			"preview_url": null,
			"track_number": 1,
			"type": "track",
			"uri": "spotify:track:4geHi4niVBx4lQ4Nku1Q3t"
		  },
		  {
			"album": {
			  "album_type": "ALBUM",
			  "artists": [
				{
				  "external_urls": {
					"spotify": "https://open.spotify.com/artist/7rXo5QTwwFBYZ5Z3veUVg8"
				  },
				  "href": "https://api.spotify.com/v1/artists/7rXo5QTwwFBYZ5Z3veUVg8",
				  "id": "7rXo5QTwwFBYZ5Z3veUVg8",
				  "name": "Texas Is The Reason",
				  "type": "artist",
				  "uri": "spotify:artist:7rXo5QTwwFBYZ5Z3veUVg8"
				}
			  ],
			  "available_markets": [
				"AD",
				"AE",
				"AG",
				"AL",
				"AM",
				"AO",
				"AR",
				"AT",
				"AU",
				"AZ",
				"BA",
				"BB",
				"BD",
				"BE",
				"BF",
				"BG",
				"BH",
				"BI",
				"BJ",
				"BN",
				"BO",
				"BR",
				"BS",
				"BT",
				"BW",
				"BY",
				"BZ",
				"CA",
				"CH",
				"CI",
				"CL",
				"CM",
				"CO",
				"CR",
				"CV",
				"CY",
				"CZ",
				"DE",
				"DJ",
				"DK",
				"DM",
				"DO",
				"DZ",
				"EC",
				"EE",
				"EG",
				"ES",
				"FI",
				"FJ",
				"FM",
				"FR",
				"GA",
				"GB",
				"GD",
				"GE",
				"GH",
				"GM",
				"GN",
				"GQ",
				"GR",
				"GT",
				"GW",
				"GY",
				"HK",
				"HN",
				"HR",
				"HT",
				"HU",
				"ID",
				"IE",
				"IL",
				"IN",
				"IS",
				"IT",
				"JM",
				"JO",
				"KE",
				"KG",
				"KH",
				"KI",
				"KM",
				"KN",
				"KR",
				"KW",
				"KZ",
				"LA",
				"LB",
				"LC",
				"LI",
				"LK",
				"LR",
				"LS",
				"LT",
				"LU",
				"LV",
				"MA",
				"MC",
				"MD",
				"MG",
				"MH",
				"MK",
				"ML",
				"MN",
				"MO",
				"MR",
				"MT",
				"MU",
				"MV",
				"MW",
				"MX",
				"MY",
				"MZ",
				"NA",
				"NE",
				"NG",
				"NI",
				"NL",
				"NO",
				"NP",
				"NR",
				"NZ",
				"OM",
				"PA",
				"PE",
				"PG",
				"PH",
				"PK",
				"PL",
				"PS",
				"PT",
				"PW",
				"PY",
				"QA",
				"RO",
				"RU",
				"RW",
				"SA",
				"SB",
				"SC",
				"SE",
				"SG",
				"SI",
				"SK",
				"SL",
				"SM",
				"SN",
				"SR",
				"ST",
				"SV",
				"SZ",
				"TD",
				"TG",
				"TH",
				"TL",
				"TN",
				"TO",
				"TR",
				"TT",
				"TV",
				"TW",
				"TZ",
				"UA",
				"UG",
				"US",
				"UY",
				"UZ",
				"VC",
				"VN",
				"VU",
				"WS",
				"ZA",
				"ZM",
				"ZW"
			  ],
			  "external_urls": {
				"spotify": "https://open.spotify.com/album/3NXykL2XzIRmMEiMKjTkN7"
			  },
			  "href": "https://api.spotify.com/v1/albums/3NXykL2XzIRmMEiMKjTkN7",
			  "id": "3NXykL2XzIRmMEiMKjTkN7",
			  "images": [
				{
				  "height": 640,
				  "url": "https://i.scdn.co/image/ab67616d0000b273198d3379f0eb1599fc6a5da1",
				  "width": 640
				},
				{
				  "height": 300,
				  "url": "https://i.scdn.co/image/ab67616d00001e02198d3379f0eb1599fc6a5da1",
				  "width": 300
				},
				{
				  "height": 64,
				  "url": "https://i.scdn.co/image/ab67616d00004851198d3379f0eb1599fc6a5da1",
				  "width": 64
				}
			  ],
			  "name": "Do You Know Who You Are?: The Complete Collection",
			  "release_date": "2013-02-12",
			  "release_date_precision": "day",
			  "total_tracks": 16,
			  "type": "album",
			  "uri": "spotify:album:3NXykL2XzIRmMEiMKjTkN7"
			},
			"artists": [
			  {
				"external_urls": {
				  "spotify": "https://open.spotify.com/artist/7rXo5QTwwFBYZ5Z3veUVg8"
				},
				"href": "https://api.spotify.com/v1/artists/7rXo5QTwwFBYZ5Z3veUVg8",
				"id": "7rXo5QTwwFBYZ5Z3veUVg8",
				"name": "Texas Is The Reason",
				"type": "artist",
				"uri": "spotify:artist:7rXo5QTwwFBYZ5Z3veUVg8"
			  }
			],
			"available_markets": [
			  "AD",
			  "AE",
			  "AG",
			  "AL",
			  "AM",
			  "AO",
			  "AR",
			  "AT",
			  "AU",
			  "AZ",
			  "BA",
			  "BB",
			  "BD",
			  "BE",
			  "BF",
			  "BG",
			  "BH",
			  "BI",
			  "BJ",
			  "BN",
			  "BO",
			  "BR",
			  "BS",
			  "BT",
			  "BW",
			  "BY",
			  "BZ",
			  "CA",
			  "CH",
			  "CI",
			  "CL",
			  "CM",
			  "CO",
			  "CR",
			  "CV",
			  "CY",
			  "CZ",
			  "DE",
			  "DJ",
			  "DK",
			  "DM",
			  "DO",
			  "DZ",
			  "EC",
			  "EE",
			  "EG",
			  "ES",
			  "FI",
			  "FJ",
			  "FM",
			  "FR",
			  "GA",
			  "GB",
			  "GD",
			  "GE",
			  "GH",
			  "GM",
			  "GN",
			  "GQ",
			  "GR",
			  "GT",
			  "GW",
			  "GY",
			  "HK",
			  "HN",
			  "HR",
			  "HT",
			  "HU",
			  "ID",
			  "IE",
			  "IL",
			  "IN",
			  "IS",
			  "IT",
			  "JM",
			  "JO",
			  "KE",
			  "KG",
			  "KH",
			  "KI",
			  "KM",
			  "KN",
			  "KR",
			  "KW",
			  "KZ",
			  "LA",
			  "LB",
			  "LC",
			  "LI",
			  "LK",
			  "LR",
			  "LS",
			  "LT",
			  "LU",
			  "LV",
			  "MA",
			  "MC",
			  "MD",
			  "MG",
			  "MH",
			  "MK",
			  "ML",
			  "MN",
			  "MO",
			  "MR",
			  "MT",
			  "MU",
			  "MV",
			  "MW",
			  "MX",
			  "MY",
			  "MZ",
			  "NA",
			  "NE",
			  "NG",
			  "NI",
			  "NL",
			  "NO",
			  "NP",
			  "NR",
			  "NZ",
			  "OM",
			  "PA",
			  "PE",
			  "PG",
			  "PH",
			  "PK",
			  "PL",
			  "PS",
			  "PT",
			  "PW",
			  "PY",
			  "QA",
			  "RO",
			  "RU",
			  "RW",
			  "SA",
			  "SB",
			  "SC",
			  "SE",
			  "SG",
			  "SI",
			  "SK",
			  "SL",
			  "SM",
			  "SN",
			  "SR",
			  "ST",
			  "SV",
			  "SZ",
			  "TD",
			  "TG",
			  "TH",
			  "TL",
			  "TN",
			  "TO",
			  "TR",
			  "TT",
			  "TV",
			  "TW",
			  "TZ",
			  "UA",
			  "UG",
			  "US",
			  "UY",
			  "UZ",
			  "VC",
			  "VN",
			  "VU",
			  "WS",
			  "ZA",
			  "ZM",
			  "ZW"
			],
			"disc_number": 1,
			"duration_ms": 282600,
			"explicit": false,
			"external_ids": {
			  "isrc": "USB4U1315109"
			},
			"external_urls": {
			  "spotify": "https://open.spotify.com/track/2VNfjz8gIoyWn5xQrNhWtp"
			},
			"href": "https://api.spotify.com/v1/tracks/2VNfjz8gIoyWn5xQrNhWtp",
			"id": "2VNfjz8gIoyWn5xQrNhWtp",
			"is_local": false,
			"name": "A Jack With One Eye",
			"popularity": 29,
			"preview_url": "https://p.scdn.co/mp3-preview/31eb95973ad444ec64fe05d3bcfbd2ca4834ae29?cid=db8c415a273c4ffc9286e12ff24b8b9f",
			"track_number": 9,
			"type": "track",
			"uri": "spotify:track:2VNfjz8gIoyWn5xQrNhWtp"
		  },
		  {
			"album": {
			  "album_type": "ALBUM",
			  "artists": [
				{
				  "external_urls": {
					"spotify": "https://open.spotify.com/artist/1Ffb6ejR6Fe5IamqA5oRUF"
				  },
				  "href": "https://api.spotify.com/v1/artists/1Ffb6ejR6Fe5IamqA5oRUF",
				  "id": "1Ffb6ejR6Fe5IamqA5oRUF",
				  "name": "Bring Me The Horizon",
				  "type": "artist",
				  "uri": "spotify:artist:1Ffb6ejR6Fe5IamqA5oRUF"
				}
			  ],
			  "available_markets": [
				"AD",
				"AE",
				"AG",
				"AL",
				"AM",
				"AO",
				"AR",
				"AT",
				"AU",
				"AZ",
				"BA",
				"BB",
				"BD",
				"BE",
				"BF",
				"BG",
				"BH",
				"BI",
				"BJ",
				"BN",
				"BO",
				"BR",
				"BS",
				"BT",
				"BW",
				"BY",
				"BZ",
				"CA",
				"CH",
				"CI",
				"CL",
				"CM",
				"CO",
				"CR",
				"CV",
				"CW",
				"CY",
				"CZ",
				"DE",
				"DJ",
				"DK",
				"DM",
				"DO",
				"DZ",
				"EC",
				"EE",
				"EG",
				"ES",
				"FI",
				"FJ",
				"FM",
				"FR",
				"GA",
				"GB",
				"GD",
				"GE",
				"GH",
				"GM",
				"GN",
				"GQ",
				"GR",
				"GT",
				"GW",
				"GY",
				"HK",
				"HN",
				"HR",
				"HT",
				"HU",
				"ID",
				"IE",
				"IL",
				"IN",
				"IS",
				"IT",
				"JM",
				"JO",
				"JP",
				"KE",
				"KG",
				"KH",
				"KI",
				"KM",
				"KN",
				"KR",
				"KW",
				"KZ",
				"LA",
				"LB",
				"LC",
				"LI",
				"LK",
				"LR",
				"LS",
				"LT",
				"LU",
				"LV",
				"MA",
				"MC",
				"MD",
				"ME",
				"MG",
				"MH",
				"MK",
				"ML",
				"MN",
				"MO",
				"MR",
				"MT",
				"MU",
				"MV",
				"MW",
				"MX",
				"MY",
				"MZ",
				"NA",
				"NE",
				"NG",
				"NI",
				"NL",
				"NO",
				"NP",
				"NR",
				"NZ",
				"OM",
				"PA",
				"PE",
				"PG",
				"PH",
				"PK",
				"PL",
				"PS",
				"PT",
				"PW",
				"PY",
				"QA",
				"RO",
				"RS",
				"RU",
				"RW",
				"SA",
				"SB",
				"SC",
				"SE",
				"SG",
				"SI",
				"SK",
				"SL",
				"SM",
				"SN",
				"SR",
				"ST",
				"SV",
				"SZ",
				"TD",
				"TG",
				"TH",
				"TL",
				"TN",
				"TO",
				"TR",
				"TT",
				"TV",
				"TW",
				"TZ",
				"UA",
				"UG",
				"US",
				"UY",
				"UZ",
				"VC",
				"VN",
				"VU",
				"WS",
				"XK",
				"ZA",
				"ZM",
				"ZW"
			  ],
			  "external_urls": {
				"spotify": "https://open.spotify.com/album/6IYPmM3xsOPL2XPSvf1ZAz"
			  },
			  "href": "https://api.spotify.com/v1/albums/6IYPmM3xsOPL2XPSvf1ZAz",
			  "id": "6IYPmM3xsOPL2XPSvf1ZAz",
			  "images": [
				{
				  "height": 640,
				  "url": "https://i.scdn.co/image/ab67616d0000b27360cf7c8dd93815ccd6cb4830",
				  "width": 640
				},
				{
				  "height": 300,
				  "url": "https://i.scdn.co/image/ab67616d00001e0260cf7c8dd93815ccd6cb4830",
				  "width": 300
				},
				{
				  "height": 64,
				  "url": "https://i.scdn.co/image/ab67616d0000485160cf7c8dd93815ccd6cb4830",
				  "width": 64
				}
			  ],
			  "name": "Sempiternal (Expanded Edition)",
			  "release_date": "2013-04-01",
			  "release_date_precision": "day",
			  "total_tracks": 13,
			  "type": "album",
			  "uri": "spotify:album:6IYPmM3xsOPL2XPSvf1ZAz"
			},
			"artists": [
			  {
				"external_urls": {
				  "spotify": "https://open.spotify.com/artist/1Ffb6ejR6Fe5IamqA5oRUF"
				},
				"href": "https://api.spotify.com/v1/artists/1Ffb6ejR6Fe5IamqA5oRUF",
				"id": "1Ffb6ejR6Fe5IamqA5oRUF",
				"name": "Bring Me The Horizon",
				"type": "artist",
				"uri": "spotify:artist:1Ffb6ejR6Fe5IamqA5oRUF"
			  }
			],
			"available_markets": [
			  "AD",
			  "AE",
			  "AG",
			  "AL",
			  "AM",
			  "AO",
			  "AR",
			  "AT",
			  "AU",
			  "AZ",
			  "BA",
			  "BB",
			  "BD",
			  "BE",
			  "BF",
			  "BG",
			  "BH",
			  "BI",
			  "BJ",
			  "BN",
			  "BO",
			  "BR",
			  "BS",
			  "BT",
			  "BW",
			  "BY",
			  "BZ",
			  "CA",
			  "CH",
			  "CI",
			  "CL",
			  "CM",
			  "CO",
			  "CR",
			  "CV",
			  "CW",
			  "CY",
			  "CZ",
			  "DE",
			  "DJ",
			  "DK",
			  "DM",
			  "DO",
			  "DZ",
			  "EC",
			  "EE",
			  "EG",
			  "ES",
			  "FI",
			  "FJ",
			  "FM",
			  "FR",
			  "GA",
			  "GB",
			  "GD",
			  "GE",
			  "GH",
			  "GM",
			  "GN",
			  "GQ",
			  "GR",
			  "GT",
			  "GW",
			  "GY",
			  "HK",
			  "HN",
			  "HR",
			  "HT",
			  "HU",
			  "ID",
			  "IE",
			  "IL",
			  "IN",
			  "IS",
			  "IT",
			  "JM",
			  "JO",
			  "JP",
			  "KE",
			  "KG",
			  "KH",
			  "KI",
			  "KM",
			  "KN",
			  "KR",
			  "KW",
			  "KZ",
			  "LA",
			  "LB",
			  "LC",
			  "LI",
			  "LK",
			  "LR",
			  "LS",
			  "LT",
			  "LU",
			  "LV",
			  "MA",
			  "MC",
			  "MD",
			  "ME",
			  "MG",
			  "MH",
			  "MK",
			  "ML",
			  "MN",
			  "MO",
			  "MR",
			  "MT",
			  "MU",
			  "MV",
			  "MW",
			  "MX",
			  "MY",
			  "MZ",
			  "NA",
			  "NE",
			  "NG",
			  "NI",
			  "NL",
			  "NO",
			  "NP",
			  "NR",
			  "NZ",
			  "OM",
			  "PA",
			  "PE",
			  "PG",
			  "PH",
			  "PK",
			  "PL",
			  "PS",
			  "PT",
			  "PW",
			  "PY",
			  "QA",
			  "RO",
			  "RS",
			  "RU",
			  "RW",
			  "SA",
			  "SB",
			  "SC",
			  "SE",
			  "SG",
			  "SI",
			  "SK",
			  "SL",
			  "SM",
			  "SN",
			  "SR",
			  "ST",
			  "SV",
			  "SZ",
			  "TD",
			  "TG",
			  "TH",
			  "TL",
			  "TN",
			  "TO",
			  "TR",
			  "TT",
			  "TV",
			  "TW",
			  "TZ",
			  "UA",
			  "UG",
			  "UY",
			  "UZ",
			  "VC",
			  "VN",
			  "VU",
			  "WS",
			  "XK",
			  "ZA",
			  "ZM",
			  "ZW"
			],
			"disc_number": 1,
			"duration_ms": 205160,
			"explicit": true,
			"external_ids": {
			  "isrc": "GBARL1202416"
			},
			"external_urls": {
			  "spotify": "https://open.spotify.com/track/7hntkdvG3jWdFKm7pGCCzd"
			},
			"href": "https://api.spotify.com/v1/tracks/7hntkdvG3jWdFKm7pGCCzd",
			"id": "7hntkdvG3jWdFKm7pGCCzd",
			"is_local": false,
			"name": "The House of Wolves",
			"popularity": 58,
			"preview_url": "https://p.scdn.co/mp3-preview/641748c0dfd6ad176eb38b93fe2eca353a787fe2?cid=db8c415a273c4ffc9286e12ff24b8b9f",
			"track_number": 2,
			"type": "track",
			"uri": "spotify:track:7hntkdvG3jWdFKm7pGCCzd"
		  },
		  {
			"album": {
			  "album_type": "ALBUM",
			  "artists": [
				{
				  "external_urls": {
					"spotify": "https://open.spotify.com/artist/5FwydyGVcsQllnM4xM6jw4"
				  },
				  "href": "https://api.spotify.com/v1/artists/5FwydyGVcsQllnM4xM6jw4",
				  "id": "5FwydyGVcsQllnM4xM6jw4",
				  "name": "American Football",
				  "type": "artist",
				  "uri": "spotify:artist:5FwydyGVcsQllnM4xM6jw4"
				}
			  ],
			  "available_markets": [
				"AD",
				"AE",
				"AG",
				"AL",
				"AM",
				"AO",
				"AR",
				"AT",
				"AU",
				"AZ",
				"BA",
				"BB",
				"BD",
				"BE",
				"BF",
				"BG",
				"BH",
				"BI",
				"BJ",
				"BN",
				"BO",
				"BR",
				"BS",
				"BT",
				"BW",
				"BY",
				"BZ",
				"CA",
				"CH",
				"CI",
				"CL",
				"CM",
				"CO",
				"CR",
				"CV",
				"CW",
				"CY",
				"CZ",
				"DE",
				"DJ",
				"DK",
				"DM",
				"DO",
				"DZ",
				"EC",
				"EE",
				"EG",
				"ES",
				"FI",
				"FJ",
				"FM",
				"FR",
				"GA",
				"GB",
				"GD",
				"GE",
				"GH",
				"GM",
				"GN",
				"GQ",
				"GR",
				"GT",
				"GW",
				"GY",
				"HK",
				"HN",
				"HR",
				"HT",
				"HU",
				"ID",
				"IE",
				"IL",
				"IN",
				"IS",
				"IT",
				"JM",
				"JO",
				"JP",
				"KE",
				"KG",
				"KH",
				"KI",
				"KM",
				"KN",
				"KR",
				"KW",
				"KZ",
				"LA",
				"LB",
				"LC",
				"LI",
				"LK",
				"LR",
				"LS",
				"LT",
				"LU",
				"LV",
				"MA",
				"MC",
				"MD",
				"ME",
				"MG",
				"MH",
				"MK",
				"ML",
				"MN",
				"MO",
				"MR",
				"MT",
				"MU",
				"MV",
				"MW",
				"MX",
				"MY",
				"MZ",
				"NA",
				"NE",
				"NG",
				"NI",
				"NL",
				"NO",
				"NP",
				"NR",
				"NZ",
				"OM",
				"PA",
				"PE",
				"PG",
				"PH",
				"PK",
				"PL",
				"PS",
				"PT",
				"PW",
				"PY",
				"QA",
				"RO",
				"RS",
				"RU",
				"RW",
				"SA",
				"SB",
				"SC",
				"SE",
				"SG",
				"SI",
				"SK",
				"SL",
				"SM",
				"SN",
				"SR",
				"ST",
				"SV",
				"SZ",
				"TD",
				"TG",
				"TH",
				"TL",
				"TN",
				"TO",
				"TR",
				"TT",
				"TV",
				"TW",
				"TZ",
				"UA",
				"UG",
				"US",
				"UY",
				"UZ",
				"VC",
				"VN",
				"VU",
				"WS",
				"XK",
				"ZA",
				"ZM",
				"ZW"
			  ],
			  "external_urls": {
				"spotify": "https://open.spotify.com/album/3wRBlpk5PRoixwOnLujTal"
			  },
			  "href": "https://api.spotify.com/v1/albums/3wRBlpk5PRoixwOnLujTal",
			  "id": "3wRBlpk5PRoixwOnLujTal",
			  "images": [
				{
				  "height": 640,
				  "url": "https://i.scdn.co/image/ab67616d0000b273d6dfafe62fef3ad433ff77d8",
				  "width": 640
				},
				{
				  "height": 300,
				  "url": "https://i.scdn.co/image/ab67616d00001e02d6dfafe62fef3ad433ff77d8",
				  "width": 300
				},
				{
				  "height": 64,
				  "url": "https://i.scdn.co/image/ab67616d00004851d6dfafe62fef3ad433ff77d8",
				  "width": 64
				}
			  ],
			  "name": "American Football",
			  "release_date": "1999",
			  "release_date_precision": "year",
			  "total_tracks": 9,
			  "type": "album",
			  "uri": "spotify:album:3wRBlpk5PRoixwOnLujTal"
			},
			"artists": [
			  {
				"external_urls": {
				  "spotify": "https://open.spotify.com/artist/5FwydyGVcsQllnM4xM6jw4"
				},
				"href": "https://api.spotify.com/v1/artists/5FwydyGVcsQllnM4xM6jw4",
				"id": "5FwydyGVcsQllnM4xM6jw4",
				"name": "American Football",
				"type": "artist",
				"uri": "spotify:artist:5FwydyGVcsQllnM4xM6jw4"
			  }
			],
			"available_markets": [
			  "AD",
			  "AE",
			  "AG",
			  "AL",
			  "AM",
			  "AO",
			  "AR",
			  "AT",
			  "AU",
			  "AZ",
			  "BA",
			  "BB",
			  "BD",
			  "BE",
			  "BF",
			  "BG",
			  "BH",
			  "BI",
			  "BJ",
			  "BN",
			  "BO",
			  "BR",
			  "BS",
			  "BT",
			  "BW",
			  "BY",
			  "BZ",
			  "CA",
			  "CH",
			  "CI",
			  "CL",
			  "CM",
			  "CO",
			  "CR",
			  "CV",
			  "CW",
			  "CY",
			  "CZ",
			  "DE",
			  "DJ",
			  "DK",
			  "DM",
			  "DO",
			  "DZ",
			  "EC",
			  "EE",
			  "EG",
			  "ES",
			  "FI",
			  "FJ",
			  "FM",
			  "FR",
			  "GA",
			  "GB",
			  "GD",
			  "GE",
			  "GH",
			  "GM",
			  "GN",
			  "GQ",
			  "GR",
			  "GT",
			  "GW",
			  "GY",
			  "HK",
			  "HN",
			  "HR",
			  "HT",
			  "HU",
			  "ID",
			  "IE",
			  "IL",
			  "IN",
			  "IS",
			  "IT",
			  "JM",
			  "JO",
			  "JP",
			  "KE",
			  "KG",
			  "KH",
			  "KI",
			  "KM",
			  "KN",
			  "KR",
			  "KW",
			  "KZ",
			  "LA",
			  "LB",
			  "LC",
			  "LI",
			  "LK",
			  "LR",
			  "LS",
			  "LT",
			  "LU",
			  "LV",
			  "MA",
			  "MC",
			  "MD",
			  "ME",
			  "MG",
			  "MH",
			  "MK",
			  "ML",
			  "MN",
			  "MO",
			  "MR",
			  "MT",
			  "MU",
			  "MV",
			  "MW",
			  "MX",
			  "MY",
			  "MZ",
			  "NA",
			  "NE",
			  "NG",
			  "NI",
			  "NL",
			  "NO",
			  "NP",
			  "NR",
			  "NZ",
			  "OM",
			  "PA",
			  "PE",
			  "PG",
			  "PH",
			  "PK",
			  "PL",
			  "PS",
			  "PT",
			  "PW",
			  "PY",
			  "QA",
			  "RO",
			  "RS",
			  "RU",
			  "RW",
			  "SA",
			  "SB",
			  "SC",
			  "SE",
			  "SG",
			  "SI",
			  "SK",
			  "SL",
			  "SM",
			  "SN",
			  "SR",
			  "ST",
			  "SV",
			  "SZ",
			  "TD",
			  "TG",
			  "TH",
			  "TL",
			  "TN",
			  "TO",
			  "TR",
			  "TT",
			  "TV",
			  "TW",
			  "TZ",
			  "UA",
			  "UG",
			  "US",
			  "UY",
			  "UZ",
			  "VC",
			  "VN",
			  "VU",
			  "WS",
			  "XK",
			  "ZA",
			  "ZM",
			  "ZW"
			],
			"disc_number": 1,
			"duration_ms": 196120,
			"explicit": false,
			"external_ids": {
			  "isrc": "US3R49900013"
			},
			"external_urls": {
			  "spotify": "https://open.spotify.com/track/6VNjaZmWzm0aRXeBE1B5mM"
			},
			"href": "https://api.spotify.com/v1/tracks/6VNjaZmWzm0aRXeBE1B5mM",
			"id": "6VNjaZmWzm0aRXeBE1B5mM",
			"is_local": false,
			"name": "For Sure",
			"popularity": 42,
			"preview_url": "https://p.scdn.co/mp3-preview/e44fa59969dd9646abfacf4894c9fdfc6ed97d21?cid=db8c415a273c4ffc9286e12ff24b8b9f",
			"track_number": 4,
			"type": "track",
			"uri": "spotify:track:6VNjaZmWzm0aRXeBE1B5mM"
		  },
		  {
			"album": {
			  "album_type": "ALBUM",
			  "artists": [
				{
				  "external_urls": {
					"spotify": "https://open.spotify.com/artist/0DK7FqcaL3ks9TfFn9y1sD"
				  },
				  "href": "https://api.spotify.com/v1/artists/0DK7FqcaL3ks9TfFn9y1sD",
				  "id": "0DK7FqcaL3ks9TfFn9y1sD",
				  "name": "Box Car Racer",
				  "type": "artist",
				  "uri": "spotify:artist:0DK7FqcaL3ks9TfFn9y1sD"
				}
			  ],
			  "available_markets": [
				"AD",
				"AE",
				"AG",
				"AL",
				"AM",
				"AO",
				"AR",
				"AT",
				"AU",
				"AZ",
				"BA",
				"BB",
				"BD",
				"BE",
				"BF",
				"BG",
				"BH",
				"BI",
				"BJ",
				"BN",
				"BO",
				"BR",
				"BS",
				"BT",
				"BW",
				"BY",
				"BZ",
				"CA",
				"CH",
				"CI",
				"CL",
				"CM",
				"CO",
				"CR",
				"CV",
				"CW",
				"CY",
				"CZ",
				"DE",
				"DJ",
				"DK",
				"DM",
				"DO",
				"DZ",
				"EC",
				"EE",
				"EG",
				"ES",
				"FI",
				"FJ",
				"FM",
				"FR",
				"GA",
				"GB",
				"GD",
				"GE",
				"GH",
				"GM",
				"GN",
				"GQ",
				"GR",
				"GT",
				"GW",
				"GY",
				"HK",
				"HN",
				"HR",
				"HT",
				"HU",
				"ID",
				"IE",
				"IL",
				"IN",
				"IS",
				"IT",
				"JM",
				"JO",
				"JP",
				"KE",
				"KG",
				"KH",
				"KI",
				"KM",
				"KN",
				"KR",
				"KW",
				"KZ",
				"LA",
				"LB",
				"LC",
				"LI",
				"LK",
				"LR",
				"LS",
				"LT",
				"LU",
				"LV",
				"MA",
				"MC",
				"MD",
				"ME",
				"MG",
				"MH",
				"MK",
				"ML",
				"MN",
				"MO",
				"MR",
				"MT",
				"MU",
				"MV",
				"MW",
				"MX",
				"MY",
				"MZ",
				"NA",
				"NE",
				"NG",
				"NI",
				"NL",
				"NO",
				"NP",
				"NR",
				"NZ",
				"OM",
				"PA",
				"PE",
				"PG",
				"PH",
				"PK",
				"PL",
				"PT",
				"PW",
				"PY",
				"QA",
				"RO",
				"RS",
				"RU",
				"RW",
				"SA",
				"SB",
				"SC",
				"SE",
				"SG",
				"SI",
				"SK",
				"SL",
				"SM",
				"SN",
				"SR",
				"ST",
				"SV",
				"SZ",
				"TD",
				"TG",
				"TH",
				"TL",
				"TN",
				"TO",
				"TR",
				"TT",
				"TV",
				"TW",
				"TZ",
				"UA",
				"UG",
				"US",
				"UY",
				"UZ",
				"VC",
				"VN",
				"VU",
				"WS",
				"XK",
				"ZA",
				"ZM",
				"ZW"
			  ],
			  "external_urls": {
				"spotify": "https://open.spotify.com/album/3gODo8aZ2dTVIaOr9SqeRE"
			  },
			  "href": "https://api.spotify.com/v1/albums/3gODo8aZ2dTVIaOr9SqeRE",
			  "id": "3gODo8aZ2dTVIaOr9SqeRE",
			  "images": [
				{
				  "height": 640,
				  "url": "https://i.scdn.co/image/ab67616d0000b2732682e92c4fc9b95df0319c72",
				  "width": 640
				},
				{
				  "height": 300,
				  "url": "https://i.scdn.co/image/ab67616d00001e022682e92c4fc9b95df0319c72",
				  "width": 300
				},
				{
				  "height": 64,
				  "url": "https://i.scdn.co/image/ab67616d000048512682e92c4fc9b95df0319c72",
				  "width": 64
				}
			  ],
			  "name": "Box Car Racer",
			  "release_date": "2002-01-01",
			  "release_date_precision": "day",
			  "total_tracks": 13,
			  "type": "album",
			  "uri": "spotify:album:3gODo8aZ2dTVIaOr9SqeRE"
			},
			"artists": [
			  {
				"external_urls": {
				  "spotify": "https://open.spotify.com/artist/0DK7FqcaL3ks9TfFn9y1sD"
				},
				"href": "https://api.spotify.com/v1/artists/0DK7FqcaL3ks9TfFn9y1sD",
				"id": "0DK7FqcaL3ks9TfFn9y1sD",
				"name": "Box Car Racer",
				"type": "artist",
				"uri": "spotify:artist:0DK7FqcaL3ks9TfFn9y1sD"
			  }
			],
			"available_markets": [
			  "AD",
			  "AE",
			  "AG",
			  "AL",
			  "AM",
			  "AO",
			  "AR",
			  "AT",
			  "AU",
			  "AZ",
			  "BA",
			  "BB",
			  "BD",
			  "BE",
			  "BF",
			  "BG",
			  "BH",
			  "BI",
			  "BJ",
			  "BN",
			  "BO",
			  "BR",
			  "BS",
			  "BT",
			  "BW",
			  "BY",
			  "BZ",
			  "CA",
			  "CH",
			  "CI",
			  "CL",
			  "CM",
			  "CO",
			  "CR",
			  "CV",
			  "CW",
			  "CY",
			  "CZ",
			  "DE",
			  "DJ",
			  "DK",
			  "DM",
			  "DO",
			  "DZ",
			  "EC",
			  "EE",
			  "EG",
			  "ES",
			  "FI",
			  "FJ",
			  "FM",
			  "FR",
			  "GA",
			  "GB",
			  "GD",
			  "GE",
			  "GH",
			  "GM",
			  "GN",
			  "GQ",
			  "GR",
			  "GT",
			  "GW",
			  "GY",
			  "HK",
			  "HN",
			  "HR",
			  "HT",
			  "HU",
			  "ID",
			  "IE",
			  "IL",
			  "IN",
			  "IS",
			  "IT",
			  "JM",
			  "JO",
			  "JP",
			  "KE",
			  "KG",
			  "KH",
			  "KI",
			  "KM",
			  "KN",
			  "KR",
			  "KW",
			  "KZ",
			  "LA",
			  "LB",
			  "LC",
			  "LI",
			  "LK",
			  "LR",
			  "LS",
			  "LT",
			  "LU",
			  "LV",
			  "MA",
			  "MC",
			  "MD",
			  "ME",
			  "MG",
			  "MH",
			  "MK",
			  "ML",
			  "MN",
			  "MO",
			  "MR",
			  "MT",
			  "MU",
			  "MV",
			  "MW",
			  "MX",
			  "MY",
			  "MZ",
			  "NA",
			  "NE",
			  "NG",
			  "NI",
			  "NL",
			  "NO",
			  "NP",
			  "NR",
			  "NZ",
			  "OM",
			  "PA",
			  "PE",
			  "PG",
			  "PH",
			  "PK",
			  "PL",
			  "PT",
			  "PW",
			  "PY",
			  "QA",
			  "RO",
			  "RS",
			  "RU",
			  "RW",
			  "SA",
			  "SB",
			  "SC",
			  "SE",
			  "SG",
			  "SI",
			  "SK",
			  "SL",
			  "SM",
			  "SN",
			  "SR",
			  "ST",
			  "SV",
			  "SZ",
			  "TD",
			  "TG",
			  "TH",
			  "TL",
			  "TN",
			  "TO",
			  "TR",
			  "TT",
			  "TV",
			  "TW",
			  "TZ",
			  "UA",
			  "UG",
			  "US",
			  "UY",
			  "UZ",
			  "VC",
			  "VN",
			  "VU",
			  "WS",
			  "XK",
			  "ZA",
			  "ZM",
			  "ZW"
			],
			"disc_number": 1,
			"duration_ms": 270866,
			"explicit": false,
			"external_ids": {
			  "isrc": "USMC10200521"
			},
			"external_urls": {
			  "spotify": "https://open.spotify.com/track/1Igy3egsujfV4WphlW0B7K"
			},
			"href": "https://api.spotify.com/v1/tracks/1Igy3egsujfV4WphlW0B7K",
			"id": "1Igy3egsujfV4WphlW0B7K",
			"is_local": false,
			"name": "I Feel So",
			"popularity": 54,
			"preview_url": null,
			"track_number": 1,
			"type": "track",
			"uri": "spotify:track:1Igy3egsujfV4WphlW0B7K"
		  },
		  {
			"album": {
			  "album_type": "COMPILATION",
			  "artists": [
				{
				  "external_urls": {
					"spotify": "https://open.spotify.com/artist/71h7GTahhKcSkQ1ayhTvOD"
				  },
				  "href": "https://api.spotify.com/v1/artists/71h7GTahhKcSkQ1ayhTvOD",
				  "id": "71h7GTahhKcSkQ1ayhTvOD",
				  "name": "Something Corporate",
				  "type": "artist",
				  "uri": "spotify:artist:71h7GTahhKcSkQ1ayhTvOD"
				}
			  ],
			  "available_markets": [
			  ],
			  "external_urls": {
				"spotify": "https://open.spotify.com/album/4AfLkc5or1PPiT8z4Pas40"
			  },
			  "href": "https://api.spotify.com/v1/albums/4AfLkc5or1PPiT8z4Pas40",
			  "id": "4AfLkc5or1PPiT8z4Pas40",
			  "images": [
				{
				  "height": 640,
				  "url": "https://i.scdn.co/image/ab67616d0000b2735ecf95727aa1f464a76ef232",
				  "width": 640
				},
				{
				  "height": 300,
				  "url": "https://i.scdn.co/image/ab67616d00001e025ecf95727aa1f464a76ef232",
				  "width": 300
				},
				{
				  "height": 64,
				  "url": "https://i.scdn.co/image/ab67616d000048515ecf95727aa1f464a76ef232",
				  "width": 64
				}
			  ],
			  "name": "Played In Space: The Best of Something Corporate",
			  "release_date": "2010-01-01",
			  "release_date_precision": "day",
			  "total_tracks": 19,
			  "type": "album",
			  "uri": "spotify:album:4AfLkc5or1PPiT8z4Pas40"
			},
			"artists": [
			  {
				"external_urls": {
				  "spotify": "https://open.spotify.com/artist/71h7GTahhKcSkQ1ayhTvOD"
				},
				"href": "https://api.spotify.com/v1/artists/71h7GTahhKcSkQ1ayhTvOD",
				"id": "71h7GTahhKcSkQ1ayhTvOD",
				"name": "Something Corporate",
				"type": "artist",
				"uri": "spotify:artist:71h7GTahhKcSkQ1ayhTvOD"
			  }
			],
			"available_markets": [
			],
			"disc_number": 1,
			"duration_ms": 266693,
			"explicit": false,
			"external_ids": {
			  "isrc": "USMC10200317"
			},
			"external_urls": {
			  "spotify": "https://open.spotify.com/track/6GiMdFEoOkr919RxfCEOlS"
			},
			"href": "https://api.spotify.com/v1/tracks/6GiMdFEoOkr919RxfCEOlS",
			"id": "6GiMdFEoOkr919RxfCEOlS",
			"is_local": false,
			"name": "I Want To Save You",
			"popularity": 23,
			"preview_url": null,
			"track_number": 8,
			"type": "track",
			"uri": "spotify:track:6GiMdFEoOkr919RxfCEOlS"
		  },
		  {
			"album": {
			  "album_type": "ALBUM",
			  "artists": [
				{
				  "external_urls": {
					"spotify": "https://open.spotify.com/artist/7iWiAD5LLKyiox2grgfmUT"
				  },
				  "href": "https://api.spotify.com/v1/artists/7iWiAD5LLKyiox2grgfmUT",
				  "id": "7iWiAD5LLKyiox2grgfmUT",
				  "name": "Bullet For My Valentine",
				  "type": "artist",
				  "uri": "spotify:artist:7iWiAD5LLKyiox2grgfmUT"
				}
			  ],
			  "available_markets": [
				"AD",
				"AE",
				"AG",
				"AL",
				"AM",
				"AO",
				"AR",
				"AT",
				"AZ",
				"BA",
				"BB",
				"BD",
				"BE",
				"BF",
				"BG",
				"BH",
				"BI",
				"BJ",
				"BN",
				"BO",
				"BR",
				"BS",
				"BT",
				"BW",
				"BY",
				"BZ",
				"CH",
				"CI",
				"CL",
				"CM",
				"CO",
				"CR",
				"CV",
				"CW",
				"CY",
				"CZ",
				"DE",
				"DJ",
				"DK",
				"DM",
				"DO",
				"DZ",
				"EC",
				"EE",
				"EG",
				"ES",
				"FI",
				"FM",
				"FR",
				"GA",
				"GB",
				"GD",
				"GE",
				"GH",
				"GM",
				"GN",
				"GQ",
				"GR",
				"GT",
				"GW",
				"GY",
				"HK",
				"HN",
				"HR",
				"HT",
				"HU",
				"ID",
				"IE",
				"IL",
				"IN",
				"IS",
				"IT",
				"JM",
				"JO",
				"JP",
				"KE",
				"KG",
				"KH",
				"KM",
				"KN",
				"KR",
				"KW",
				"KZ",
				"LA",
				"LB",
				"LC",
				"LI",
				"LK",
				"LR",
				"LS",
				"LT",
				"LU",
				"LV",
				"MA",
				"MC",
				"MD",
				"ME",
				"MG",
				"MK",
				"ML",
				"MN",
				"MO",
				"MR",
				"MT",
				"MU",
				"MV",
				"MW",
				"MX",
				"MY",
				"MZ",
				"NA",
				"NE",
				"NG",
				"NI",
				"NL",
				"NO",
				"NP",
				"OM",
				"PA",
				"PE",
				"PH",
				"PK",
				"PL",
				"PS",
				"PT",
				"PY",
				"QA",
				"RO",
				"RS",
				"RU",
				"RW",
				"SA",
				"SC",
				"SE",
				"SG",
				"SI",
				"SK",
				"SL",
				"SM",
				"SN",
				"SR",
				"ST",
				"SV",
				"SZ",
				"TD",
				"TG",
				"TH",
				"TL",
				"TN",
				"TR",
				"TT",
				"TW",
				"TZ",
				"UA",
				"UG",
				"UY",
				"UZ",
				"VC",
				"VN",
				"XK",
				"ZA",
				"ZM",
				"ZW"
			  ],
			  "external_urls": {
				"spotify": "https://open.spotify.com/album/7x5pD3rNP9ATJbQzvvm7Lo"
			  },
			  "href": "https://api.spotify.com/v1/albums/7x5pD3rNP9ATJbQzvvm7Lo",
			  "id": "7x5pD3rNP9ATJbQzvvm7Lo",
			  "images": [
				{
				  "height": 640,
				  "url": "https://i.scdn.co/image/ab67616d0000b2736b997d8f2a6ea90813d6e67e",
				  "width": 640
				},
				{
				  "height": 300,
				  "url": "https://i.scdn.co/image/ab67616d00001e026b997d8f2a6ea90813d6e67e",
				  "width": 300
				},
				{
				  "height": 64,
				  "url": "https://i.scdn.co/image/ab67616d000048516b997d8f2a6ea90813d6e67e",
				  "width": 64
				}
			  ],
			  "name": "Scream Aim Fire Deluxe Edition",
			  "release_date": "2008-11-28",
			  "release_date_precision": "day",
			  "total_tracks": 15,
			  "type": "album",
			  "uri": "spotify:album:7x5pD3rNP9ATJbQzvvm7Lo"
			},
			"artists": [
			  {
				"external_urls": {
				  "spotify": "https://open.spotify.com/artist/7iWiAD5LLKyiox2grgfmUT"
				},
				"href": "https://api.spotify.com/v1/artists/7iWiAD5LLKyiox2grgfmUT",
				"id": "7iWiAD5LLKyiox2grgfmUT",
				"name": "Bullet For My Valentine",
				"type": "artist",
				"uri": "spotify:artist:7iWiAD5LLKyiox2grgfmUT"
			  }
			],
			"available_markets": [
			  "AD",
			  "AE",
			  "AG",
			  "AL",
			  "AM",
			  "AO",
			  "AR",
			  "AT",
			  "AZ",
			  "BA",
			  "BB",
			  "BD",
			  "BE",
			  "BF",
			  "BG",
			  "BH",
			  "BI",
			  "BJ",
			  "BN",
			  "BO",
			  "BR",
			  "BS",
			  "BT",
			  "BW",
			  "BY",
			  "BZ",
			  "CH",
			  "CI",
			  "CL",
			  "CM",
			  "CO",
			  "CR",
			  "CV",
			  "CW",
			  "CY",
			  "CZ",
			  "DE",
			  "DJ",
			  "DK",
			  "DM",
			  "DO",
			  "DZ",
			  "EC",
			  "EE",
			  "EG",
			  "ES",
			  "FI",
			  "FM",
			  "FR",
			  "GA",
			  "GB",
			  "GD",
			  "GE",
			  "GH",
			  "GM",
			  "GN",
			  "GQ",
			  "GR",
			  "GT",
			  "GW",
			  "GY",
			  "HK",
			  "HN",
			  "HR",
			  "HT",
			  "HU",
			  "ID",
			  "IE",
			  "IL",
			  "IN",
			  "IS",
			  "IT",
			  "JM",
			  "JO",
			  "JP",
			  "KE",
			  "KG",
			  "KH",
			  "KM",
			  "KN",
			  "KR",
			  "KW",
			  "KZ",
			  "LA",
			  "LB",
			  "LC",
			  "LI",
			  "LK",
			  "LR",
			  "LS",
			  "LT",
			  "LU",
			  "LV",
			  "MA",
			  "MC",
			  "MD",
			  "ME",
			  "MG",
			  "MK",
			  "ML",
			  "MN",
			  "MO",
			  "MR",
			  "MT",
			  "MU",
			  "MV",
			  "MW",
			  "MX",
			  "MY",
			  "MZ",
			  "NA",
			  "NE",
			  "NG",
			  "NI",
			  "NL",
			  "NO",
			  "NP",
			  "OM",
			  "PA",
			  "PE",
			  "PH",
			  "PK",
			  "PL",
			  "PS",
			  "PT",
			  "PY",
			  "QA",
			  "RO",
			  "RS",
			  "RU",
			  "RW",
			  "SA",
			  "SC",
			  "SE",
			  "SG",
			  "SI",
			  "SK",
			  "SL",
			  "SM",
			  "SN",
			  "SR",
			  "ST",
			  "SV",
			  "SZ",
			  "TD",
			  "TG",
			  "TH",
			  "TL",
			  "TN",
			  "TR",
			  "TT",
			  "TW",
			  "TZ",
			  "UA",
			  "UG",
			  "UY",
			  "UZ",
			  "VC",
			  "VN",
			  "XK",
			  "ZA",
			  "ZM",
			  "ZW"
			],
			"disc_number": 1,
			"duration_ms": 297946,
			"explicit": true,
			"external_ids": {
			  "isrc": "GBHQD0700048"
			},
			"external_urls": {
			  "spotify": "https://open.spotify.com/track/1OqDUHFotTmZQ0khBRHnK2"
			},
			"href": "https://api.spotify.com/v1/tracks/1OqDUHFotTmZQ0khBRHnK2",
			"id": "1OqDUHFotTmZQ0khBRHnK2",
			"is_local": false,
			"name": "Hearts Burst into Fire",
			"popularity": 45,
			"preview_url": "https://p.scdn.co/mp3-preview/e6b2fa3166dace6334d2f546d1e6ad0e17370dc0?cid=db8c415a273c4ffc9286e12ff24b8b9f",
			"track_number": 3,
			"type": "track",
			"uri": "spotify:track:1OqDUHFotTmZQ0khBRHnK2"
		  },
		  {
			"album": {
			  "album_type": "ALBUM",
			  "artists": [
				{
				  "external_urls": {
					"spotify": "https://open.spotify.com/artist/2lZkXWxkZsZzBocxMjN1or"
				  },
				  "href": "https://api.spotify.com/v1/artists/2lZkXWxkZsZzBocxMjN1or",
				  "id": "2lZkXWxkZsZzBocxMjN1or",
				  "name": "Sunny Day Real Estate",
				  "type": "artist",
				  "uri": "spotify:artist:2lZkXWxkZsZzBocxMjN1or"
				}
			  ],
			  "available_markets": [
			  ],
			  "external_urls": {
				"spotify": "https://open.spotify.com/album/6c7gEp8KqjMsTmvloivm59"
			  },
			  "href": "https://api.spotify.com/v1/albums/6c7gEp8KqjMsTmvloivm59",
			  "id": "6c7gEp8KqjMsTmvloivm59",
			  "images": [
				{
				  "height": 640,
				  "url": "https://i.scdn.co/image/ab67616d0000b273c44ebd61d8bd575a9e49825e",
				  "width": 640
				},
				{
				  "height": 300,
				  "url": "https://i.scdn.co/image/ab67616d00001e02c44ebd61d8bd575a9e49825e",
				  "width": 300
				},
				{
				  "height": 64,
				  "url": "https://i.scdn.co/image/ab67616d00004851c44ebd61d8bd575a9e49825e",
				  "width": 64
				}
			  ],
			  "name": "Diary (2009 Edition)",
			  "release_date": "1994-05-10",
			  "release_date_precision": "day",
			  "total_tracks": 13,
			  "type": "album",
			  "uri": "spotify:album:6c7gEp8KqjMsTmvloivm59"
			},
			"artists": [
			  {
				"external_urls": {
				  "spotify": "https://open.spotify.com/artist/2lZkXWxkZsZzBocxMjN1or"
				},
				"href": "https://api.spotify.com/v1/artists/2lZkXWxkZsZzBocxMjN1or",
				"id": "2lZkXWxkZsZzBocxMjN1or",
				"name": "Sunny Day Real Estate",
				"type": "artist",
				"uri": "spotify:artist:2lZkXWxkZsZzBocxMjN1or"
			  }
			],
			"available_markets": [
			],
			"disc_number": 1,
			"duration_ms": 347413,
			"explicit": false,
			"external_ids": {
			  "isrc": "USSUB0984611"
			},
			"external_urls": {
			  "spotify": "https://open.spotify.com/track/0KjxBmeyMFuJsK7VVqXbIO"
			},
			"href": "https://api.spotify.com/v1/tracks/0KjxBmeyMFuJsK7VVqXbIO",
			"id": "0KjxBmeyMFuJsK7VVqXbIO",
			"is_local": false,
			"name": "Sometimes",
			"popularity": 0,
			"preview_url": null,
			"track_number": 11,
			"type": "track",
			"uri": "spotify:track:0KjxBmeyMFuJsK7VVqXbIO"
		  },
		  {
			"album": {
			  "album_type": "ALBUM",
			  "artists": [
				{
				  "external_urls": {
					"spotify": "https://open.spotify.com/artist/74XFHRwlV6OrjEM0A2NCMF"
				  },
				  "href": "https://api.spotify.com/v1/artists/74XFHRwlV6OrjEM0A2NCMF",
				  "id": "74XFHRwlV6OrjEM0A2NCMF",
				  "name": "Paramore",
				  "type": "artist",
				  "uri": "spotify:artist:74XFHRwlV6OrjEM0A2NCMF"
				}
			  ],
			  "available_markets": [
				"BR",
				"CA",
				"US"
			  ],
			  "external_urls": {
				"spotify": "https://open.spotify.com/album/71rziY9eLo1tA2dBMxrwhc"
			  },
			  "href": "https://api.spotify.com/v1/albums/71rziY9eLo1tA2dBMxrwhc",
			  "id": "71rziY9eLo1tA2dBMxrwhc",
			  "images": [
				{
				  "height": 640,
				  "url": "https://i.scdn.co/image/ab67616d0000b273bee754528c08d5ff6799a1eb",
				  "width": 640
				},
				{
				  "height": 300,
				  "url": "https://i.scdn.co/image/ab67616d00001e02bee754528c08d5ff6799a1eb",
				  "width": 300
				},
				{
				  "height": 64,
				  "url": "https://i.scdn.co/image/ab67616d00004851bee754528c08d5ff6799a1eb",
				  "width": 64
				}
			  ],
			  "name": "Riot!",
			  "release_date": "2007-06-11",
			  "release_date_precision": "day",
			  "total_tracks": 12,
			  "type": "album",
			  "uri": "spotify:album:71rziY9eLo1tA2dBMxrwhc"
			},
			"artists": [
			  {
				"external_urls": {
				  "spotify": "https://open.spotify.com/artist/74XFHRwlV6OrjEM0A2NCMF"
				},
				"href": "https://api.spotify.com/v1/artists/74XFHRwlV6OrjEM0A2NCMF",
				"id": "74XFHRwlV6OrjEM0A2NCMF",
				"name": "Paramore",
				"type": "artist",
				"uri": "spotify:artist:74XFHRwlV6OrjEM0A2NCMF"
			  }
			],
			"available_markets": [
			  "BR",
			  "CA",
			  "US"
			],
			"disc_number": 1,
			"duration_ms": 198226,
			"explicit": false,
			"external_ids": {
			  "isrc": "USAT20702604"
			},
			"external_urls": {
			  "spotify": "https://open.spotify.com/track/7fx2rt43UfclOOulPwBYk2"
			},
			"href": "https://api.spotify.com/v1/tracks/7fx2rt43UfclOOulPwBYk2",
			"id": "7fx2rt43UfclOOulPwBYk2",
			"is_local": false,
			"name": "Let the Flames Begin",
			"popularity": 54,
			"preview_url": "https://p.scdn.co/mp3-preview/32f515593d05a17ce965a77dbed63fcc7d0b8901?cid=db8c415a273c4ffc9286e12ff24b8b9f",
			"track_number": 6,
			"type": "track",
			"uri": "spotify:track:7fx2rt43UfclOOulPwBYk2"
		  },
		  {
			"album": {
			  "album_type": "ALBUM",
			  "artists": [
				{
				  "external_urls": {
					"spotify": "https://open.spotify.com/artist/4UXqAaa6dQYAk18Lv7PEgX"
				  },
				  "href": "https://api.spotify.com/v1/artists/4UXqAaa6dQYAk18Lv7PEgX",
				  "id": "4UXqAaa6dQYAk18Lv7PEgX",
				  "name": "Fall Out Boy",
				  "type": "artist",
				  "uri": "spotify:artist:4UXqAaa6dQYAk18Lv7PEgX"
				}
			  ],
			  "available_markets": [
				"AD",
				"AE",
				"AG",
				"AL",
				"AM",
				"AO",
				"AR",
				"AT",
				"AU",
				"AZ",
				"BA",
				"BB",
				"BD",
				"BE",
				"BF",
				"BG",
				"BH",
				"BI",
				"BJ",
				"BN",
				"BO",
				"BR",
				"BS",
				"BT",
				"BW",
				"BY",
				"BZ",
				"CA",
				"CH",
				"CI",
				"CL",
				"CM",
				"CO",
				"CR",
				"CV",
				"CW",
				"CY",
				"CZ",
				"DE",
				"DJ",
				"DK",
				"DM",
				"DO",
				"DZ",
				"EC",
				"EE",
				"EG",
				"ES",
				"FI",
				"FJ",
				"FM",
				"FR",
				"GA",
				"GB",
				"GD",
				"GE",
				"GH",
				"GM",
				"GN",
				"GQ",
				"GR",
				"GT",
				"GW",
				"GY",
				"HK",
				"HN",
				"HR",
				"HT",
				"HU",
				"ID",
				"IE",
				"IL",
				"IN",
				"IS",
				"IT",
				"JM",
				"JO",
				"JP",
				"KE",
				"KG",
				"KH",
				"KI",
				"KM",
				"KN",
				"KR",
				"KW",
				"KZ",
				"LA",
				"LB",
				"LC",
				"LI",
				"LK",
				"LR",
				"LS",
				"LT",
				"LU",
				"LV",
				"MA",
				"MC",
				"MD",
				"ME",
				"MG",
				"MH",
				"MK",
				"ML",
				"MN",
				"MO",
				"MR",
				"MT",
				"MU",
				"MV",
				"MW",
				"MX",
				"MY",
				"MZ",
				"NA",
				"NE",
				"NG",
				"NI",
				"NL",
				"NO",
				"NP",
				"NR",
				"NZ",
				"OM",
				"PA",
				"PE",
				"PG",
				"PH",
				"PK",
				"PL",
				"PS",
				"PT",
				"PW",
				"PY",
				"QA",
				"RO",
				"RS",
				"RU",
				"RW",
				"SA",
				"SB",
				"SC",
				"SE",
				"SG",
				"SI",
				"SK",
				"SL",
				"SM",
				"SN",
				"SR",
				"ST",
				"SV",
				"SZ",
				"TD",
				"TG",
				"TH",
				"TL",
				"TN",
				"TO",
				"TR",
				"TT",
				"TV",
				"TW",
				"TZ",
				"UA",
				"UG",
				"US",
				"UY",
				"UZ",
				"VC",
				"VN",
				"VU",
				"WS",
				"XK",
				"ZA",
				"ZM",
				"ZW"
			  ],
			  "external_urls": {
				"spotify": "https://open.spotify.com/album/7l4nnHG7upOnUM4WvAjToY"
			  },
			  "href": "https://api.spotify.com/v1/albums/7l4nnHG7upOnUM4WvAjToY",
			  "id": "7l4nnHG7upOnUM4WvAjToY",
			  "images": [
				{
				  "height": 640,
				  "url": "https://i.scdn.co/image/ab67616d0000b2733acad60fe6e2daf27e6b0034",
				  "width": 640
				},
				{
				  "height": 300,
				  "url": "https://i.scdn.co/image/ab67616d00001e023acad60fe6e2daf27e6b0034",
				  "width": 300
				},
				{
				  "height": 64,
				  "url": "https://i.scdn.co/image/ab67616d000048513acad60fe6e2daf27e6b0034",
				  "width": 64
				}
			  ],
			  "name": "Take This To Your Grave",
			  "release_date": "2003-05-06",
			  "release_date_precision": "day",
			  "total_tracks": 12,
			  "type": "album",
			  "uri": "spotify:album:7l4nnHG7upOnUM4WvAjToY"
			},
			"artists": [
			  {
				"external_urls": {
				  "spotify": "https://open.spotify.com/artist/4UXqAaa6dQYAk18Lv7PEgX"
				},
				"href": "https://api.spotify.com/v1/artists/4UXqAaa6dQYAk18Lv7PEgX",
				"id": "4UXqAaa6dQYAk18Lv7PEgX",
				"name": "Fall Out Boy",
				"type": "artist",
				"uri": "spotify:artist:4UXqAaa6dQYAk18Lv7PEgX"
			  }
			],
			"available_markets": [
			  "AD",
			  "AE",
			  "AG",
			  "AL",
			  "AM",
			  "AO",
			  "AR",
			  "AT",
			  "AU",
			  "AZ",
			  "BA",
			  "BB",
			  "BD",
			  "BE",
			  "BF",
			  "BG",
			  "BH",
			  "BI",
			  "BJ",
			  "BN",
			  "BO",
			  "BR",
			  "BS",
			  "BT",
			  "BW",
			  "BY",
			  "BZ",
			  "CA",
			  "CH",
			  "CI",
			  "CL",
			  "CM",
			  "CO",
			  "CR",
			  "CV",
			  "CW",
			  "CY",
			  "CZ",
			  "DE",
			  "DJ",
			  "DK",
			  "DM",
			  "DO",
			  "DZ",
			  "EC",
			  "EE",
			  "EG",
			  "ES",
			  "FI",
			  "FJ",
			  "FM",
			  "FR",
			  "GA",
			  "GB",
			  "GD",
			  "GE",
			  "GH",
			  "GM",
			  "GN",
			  "GQ",
			  "GR",
			  "GT",
			  "GW",
			  "GY",
			  "HK",
			  "HN",
			  "HR",
			  "HT",
			  "HU",
			  "ID",
			  "IE",
			  "IL",
			  "IN",
			  "IS",
			  "IT",
			  "JM",
			  "JO",
			  "JP",
			  "KE",
			  "KG",
			  "KH",
			  "KI",
			  "KM",
			  "KN",
			  "KR",
			  "KW",
			  "KZ",
			  "LA",
			  "LB",
			  "LC",
			  "LI",
			  "LK",
			  "LR",
			  "LS",
			  "LT",
			  "LU",
			  "LV",
			  "MA",
			  "MC",
			  "MD",
			  "ME",
			  "MG",
			  "MH",
			  "MK",
			  "ML",
			  "MN",
			  "MO",
			  "MR",
			  "MT",
			  "MU",
			  "MV",
			  "MW",
			  "MX",
			  "MY",
			  "MZ",
			  "NA",
			  "NE",
			  "NG",
			  "NI",
			  "NL",
			  "NO",
			  "NP",
			  "NR",
			  "NZ",
			  "OM",
			  "PA",
			  "PE",
			  "PG",
			  "PH",
			  "PK",
			  "PL",
			  "PS",
			  "PT",
			  "PW",
			  "PY",
			  "QA",
			  "RO",
			  "RS",
			  "RU",
			  "RW",
			  "SA",
			  "SB",
			  "SC",
			  "SE",
			  "SG",
			  "SI",
			  "SK",
			  "SL",
			  "SM",
			  "SN",
			  "SR",
			  "ST",
			  "SV",
			  "SZ",
			  "TD",
			  "TG",
			  "TH",
			  "TL",
			  "TN",
			  "TO",
			  "TR",
			  "TT",
			  "TV",
			  "TW",
			  "TZ",
			  "UA",
			  "UG",
			  "US",
			  "UY",
			  "UZ",
			  "VC",
			  "VN",
			  "VU",
			  "WS",
			  "XK",
			  "ZA",
			  "ZM",
			  "ZW"
			],
			"disc_number": 1,
			"duration_ms": 141336,
			"explicit": false,
			"external_ids": {
			  "isrc": "US56V0506111"
			},
			"external_urls": {
			  "spotify": "https://open.spotify.com/track/4tj6uekOEtNOqJJ8BpBP74"
			},
			"href": "https://api.spotify.com/v1/tracks/4tj6uekOEtNOqJJ8BpBP74",
			"id": "4tj6uekOEtNOqJJ8BpBP74",
			"is_local": false,
			"name": "Reinventing the Wheel to Run Myself Over",
			"popularity": 44,
			"preview_url": "https://p.scdn.co/mp3-preview/0ea2546751e0d53efbf4cc8efd5d8c7bbac70cdd?cid=db8c415a273c4ffc9286e12ff24b8b9f",
			"track_number": 11,
			"type": "track",
			"uri": "spotify:track:4tj6uekOEtNOqJJ8BpBP74"
		  }
		],
		"seeds": [
		  {
			"initialPoolSize": 1003,
			"afterFilteringSize": 1003,
			"afterRelinkingSize": 1003,
			"id": "emo",
			"type": "GENRE",
			"href": null
		  }
		]
	  }`
)
